// =============================================================================
// Skydiving Operations — mock data
// Jump planes, jump pilots, regular jumpers, prospects, education programs
//
// Ontology mirrors glider ops & training modules:
//   Personnel → jump pilots (rated, current)
//   Aircraft  → jump planes (fleet, W&B, status)
//   Students  → jumpers (experience, ratings, weights) + prospects
//   Programs  → USPA license progression + tandem / AFF / static-line
// =============================================================================

const today = new Date('2026-03-29')
const daysFrom   = (d) => new Date(today.getTime() + d * 86_400_000).toISOString().split('T')[0]
const daysBefore = (d) => daysFrom(-d)

// ── Drop Zone Info ────────────────────────────────────────────────────────────

export const DZ_INFO = {
  name:          'Front Range Skydivers',
  tagline:       'Jump the Rockies',
  address:       '5534 Independence Rd, Boulder, CO 80301',
  airport:       'Boulder Municipal Airport (KBDU)',
  phone:         '(303) 527-2255',
  email:         'jump@frontrangeskydivers.com',
  website:       'https://www.frontrangeskydivers.com',
  established:   2012,
  hours:         'Thu–Mon · Mar–Nov, weather permitting',
  fieldElevation:'5,288 ft MSL',
  jumpAltitudes: '10,000 – 14,000 ft AGL',
  uspaGroupMember: true,
  uspaNumber:    'D-142',
}

// ── Jump Plane Fleet ──────────────────────────────────────────────────────────

export const JUMP_PLANES = [
  {
    id:          'jp-001',
    type:        'Cessna 208B Grand Caravan',
    tailNumber:  'N208JB',
    seats:        15,                       // jumper capacity
    role:        'Primary jump ship',
    status:      'airworthy',
    notes:       'Turbine workhorse — 15 jumpers to 14k in ~18 min',
    maxGross:    8750,
    emptyWeight: 4570,
    usefulLoad:  4180,
    climbRate:   '900 fpm loaded',
    jumpDoor:    'Rear ramp + side door',
    img:         'c208-jump',
  },
  {
    id:          'jp-002',
    type:        'de Havilland DHC-6 Twin Otter',
    tailNumber:  'N406DZ',
    seats:        23,
    role:        'High-capacity jump ship',
    status:      'airworthy',
    notes:       'Twin turboprop — used for big-way events & boogies',
    maxGross:    12500,
    emptyWeight: 7400,
    usefulLoad:  5100,
    climbRate:   '1,100 fpm loaded',
    jumpDoor:    'Rear ramp',
    img:         'dhc6-jump',
  },
  {
    id:          'jp-003',
    type:        'Cessna 182 Skylane',
    tailNumber:  'N182JK',
    seats:        4,
    role:        'Small-load / student hops',
    status:      'airworthy',
    notes:       'Piston single — static-line & hop-n-pop loads',
    maxGross:    2950,
    emptyWeight: 1810,
    usefulLoad:  1140,
    climbRate:   '600 fpm loaded',
    jumpDoor:    'Modified right-side door',
    img:         'c182-jump',
  },
  {
    id:          'jp-004',
    type:        'PAC 750XL',
    tailNumber:  'N750XL',
    seats:        16,
    role:        'Backup / event overflow',
    status:      'maintenance',
    notes:       'Turboprop — in annual inspection, return ~2 weeks',
    maxGross:    7500,
    emptyWeight: 3510,
    usefulLoad:  3990,
    climbRate:   '850 fpm loaded',
    jumpDoor:    'Sliding left door',
    img:         'pac750-jump',
  },
]

// ── Jump Pilots ───────────────────────────────────────────────────────────────

export const JUMP_PILOTS = [
  {
    id:            'jp-pil-001',
    name:          'Rick Hennessy',
    role:          'Chief Jump Pilot',
    weightLbs:     185,
    certificateNumber: 'ATP-221890',
    certType:      'ATP',
    ratings:       ['ASEL', 'AMEL', 'SES'],
    medicalClass:  1,
    medicalExpiry: daysFrom(280),
    totalHours:    6200,
    jumpPilotHours:3800,
    aircraftTypesQual: ['jp-001', 'jp-002', 'jp-003', 'jp-004'],
    uspaRating:    'D',
    ownJumps:      420,
    status:        'active',
    notes:         'Formation load separation specialist. DZ safety officer.',
  },
  {
    id:            'jp-pil-002',
    name:          'Megan Torres',
    role:          'Jump Pilot',
    weightLbs:     142,
    certificateNumber: 'COM-338821',
    certType:      'Commercial',
    ratings:       ['ASEL', 'AMEL'],
    medicalClass:  2,
    medicalExpiry: daysFrom(190),
    totalHours:    2400,
    jumpPilotHours:1100,
    aircraftTypesQual: ['jp-001', 'jp-003'],
    uspaRating:    'C',
    ownJumps:      215,
    status:        'active',
    notes:         'Weekday primary Caravan pilot. Also rated tow pilot.',
  },
  {
    id:            'jp-pil-003',
    name:          'Calvin Briggs',
    role:          'Jump Pilot',
    weightLbs:     198,
    certificateNumber: 'COM-447712',
    certType:      'Commercial',
    ratings:       ['ASEL', 'AMEL', 'Instrument'],
    medicalClass:  2,
    medicalExpiry: daysFrom(95),
    totalHours:    1800,
    jumpPilotHours:650,
    aircraftTypesQual: ['jp-001', 'jp-002', 'jp-004'],
    uspaRating:    'B',
    ownJumps:      110,
    status:        'active',
    notes:         'Twin Otter qualified. Weekend & boogie loads.',
  },
  {
    id:            'jp-pil-004',
    name:          'Diane Kowalski',
    role:          'Jump Pilot (Part-time)',
    weightLbs:     155,
    certificateNumber: 'COM-510093',
    certType:      'Commercial',
    ratings:       ['ASEL'],
    medicalClass:  2,
    medicalExpiry: daysFrom(310),
    totalHours:    950,
    jumpPilotHours:280,
    aircraftTypesQual: ['jp-003'],
    uspaRating:    'A',
    ownJumps:      35,
    status:        'active',
    notes:         'C182 only. Building hours toward Caravan checkout.',
  },
]

// ── USPA License Progression (Education Programs) ────────────────────────────

export const JUMP_PROGRAMS = {
  tandem: {
    id:          'tandem',
    name:        'Tandem Skydive',
    icon:        '🪂',
    description: 'Your first jump — harnessed to an instructor from 14,000 ft. No experience needed.',
    pricePerJump: 250,
    videoPackage: 120,
    altitudeFt:  14000,
    freefallTime:'~60 sec',
    requirements: [],
    uspaCredit:  false,
  },

  aff: {
    id:          'aff',
    name:        'Accelerated Freefall (AFF)',
    icon:        '🎓',
    reg:         'USPA SIM Section 4',
    description: 'Solo freefall from day one with two instructors. 7-level progression to A-license.',
    pricePerLevel: [
      { level: 1, label: 'Category A — Ground school + first jump', price: 350 },
      { level: 2, label: 'Category B — Practice pulls, altitude awareness', price: 280 },
      { level: 3, label: 'Category C — Solo exit, heading control', price: 280 },
      { level: 4, label: 'Category D — 360° turns, docking', price: 250 },
      { level: 5, label: 'Category E — Forward movement, tracking', price: 250 },
      { level: 6, label: 'Category F — Back loops, barrel rolls', price: 250 },
      { level: 7, label: 'Category G — Hop-n-pop, self-supervision', price: 220 },
    ],
    groundSchoolHrs: 6,
    typicalCost: { min: 1880, avg: 2800 },
    requirements: [
      { id: 'min_age',  label: 'Minimum age 18', unit: 'years' },
      { id: 'weight',   label: 'Max weight 230 lbs', unit: 'lbs' },
      { id: 'medical',  label: 'No medical restrictions affecting skydiving' },
    ],
  },

  static_line: {
    id:          'static_line',
    name:        'Static-Line / IAD',
    icon:        '📋',
    reg:         'USPA SIM Section 4',
    description: 'Instructor-aided deployment — parachute opens automatically on exit. 5-jump progression before freefall.',
    pricePerJump: 180,
    groundSchoolHrs: 5,
    typicalCost: { min: 900, avg: 1400 },
    jumpsBeforeFreefall: 5,
    requirements: [
      { id: 'min_age',  label: 'Minimum age 18', unit: 'years' },
      { id: 'weight',   label: 'Max weight 230 lbs', unit: 'lbs' },
    ],
  },

  a_license: {
    id:          'a_license',
    name:        'USPA A License',
    icon:        '🅰️',
    reg:         'USPA SIM Section 3-1',
    description: 'First solo skydiving license. Jump without instructor supervision at any USPA DZ.',
    minJumps:    25,
    requirements: [
      { id: 'jumps',        label: 'Minimum 25 jumps',              min: 25,  unit: 'jumps' },
      { id: 'freefall',     label: 'Freefall time ≥ 20 min',       min: 20,  unit: 'min' },
      { id: 'canopy',       label: 'Canopy accuracy landing ≤15 m', min: 1,   unit: 'demo' },
      { id: 'water_train',  label: 'Water training completed',      min: 1,   unit: 'session' },
      { id: 'packing',      label: 'Pack 20 main canopies',         min: 20,  unit: 'packs' },
      { id: 'oral_exam',    label: 'Oral exam passed',              min: 1,   unit: 'exam' },
    ],
  },

  b_license: {
    id:          'b_license',
    name:        'USPA B License',
    icon:        '🅱️',
    reg:         'USPA SIM Section 3-1',
    description: 'Intermediate license — night jumps, water jumps, demo eligibility.',
    minJumps:    50,
    requirements: [
      { id: 'jumps',        label: 'Minimum 50 jumps',             min: 50,  unit: 'jumps' },
      { id: 'freefall',     label: 'Freefall time ≥ 30 min',      min: 30,  unit: 'min' },
      { id: 'accuracy',     label: 'Accuracy series (10 jumps)',   min: 10,  unit: 'jumps' },
      { id: 'canopy_course',label: 'Canopy course completed',      min: 1,   unit: 'course' },
      { id: 'written_exam', label: 'Written exam passed',          min: 1,   unit: 'exam' },
    ],
  },

  c_license: {
    id:          'c_license',
    name:        'USPA C License',
    icon:        '©️',
    reg:         'USPA SIM Section 3-1',
    description: 'Advanced license — formation skydiving, demo jumps, wingsuiting eligibility.',
    minJumps:    200,
    requirements: [
      { id: 'jumps',        label: 'Minimum 200 jumps',            min: 200, unit: 'jumps' },
      { id: 'freefall',     label: 'Freefall time ≥ 60 min',      min: 60,  unit: 'min' },
      { id: 'night_jump',   label: 'Night jump completed',         min: 1,   unit: 'jump' },
      { id: 'formation',    label: 'Formation skydiving (4-way)',  min: 1,   unit: 'event' },
      { id: 'written_exam', label: 'Written exam passed',          min: 1,   unit: 'exam' },
    ],
  },

  d_license: {
    id:          'd_license',
    name:        'USPA D License',
    icon:        '🏅',
    reg:         'USPA SIM Section 3-1',
    description: 'Expert license — highest USPA rating. Eligible for all disciplines, instruction, and competition.',
    minJumps:    500,
    requirements: [
      { id: 'jumps',        label: 'Minimum 500 jumps',            min: 500, unit: 'jumps' },
      { id: 'freefall',     label: 'Freefall time ≥ 3 hrs',       min: 180, unit: 'min' },
      { id: 'night_jump',   label: '2 night jumps completed',      min: 2,   unit: 'jumps' },
      { id: 'live_water',   label: 'Intentional water jump',       min: 1,   unit: 'jump' },
      { id: 'written_exam', label: 'Written exam passed',          min: 1,   unit: 'exam' },
    ],
  },

  tandem_instructor: {
    id:          'tandem_instructor',
    name:        'Tandem Instructor Rating',
    icon:        '👨‍🏫',
    reg:         'USPA SIM Section 6',
    description: 'USPA Tandem Instructor certification — requires D-license + 500 jumps + manufacturer course.',
    minJumps:    500,
    requirements: [
      { id: 'jumps',        label: 'Minimum 500 jumps',            min: 500, unit: 'jumps' },
      { id: 'd_license',    label: 'USPA D License',               min: 1,   unit: 'cert' },
      { id: 'mfg_course',   label: 'Manufacturer tandem course',   min: 1,   unit: 'course' },
      { id: 'faa_medical',  label: 'FAA Class 3 medical (or BasicMed)', min: 1, unit: 'cert' },
    ],
  },

  aff_instructor: {
    id:          'aff_instructor',
    name:        'AFF Instructor Rating',
    icon:        '🎖️',
    reg:         'USPA SIM Section 6',
    description: 'USPA AFF Instructor certification — mentor new jumpers through solo freefall progression.',
    minJumps:    500,
    requirements: [
      { id: 'jumps',        label: 'Minimum 500 jumps',            min: 500, unit: 'jumps' },
      { id: 'd_license',    label: 'USPA D License',               min: 1,   unit: 'cert' },
      { id: 'ie_course',    label: 'USPA I/E course completed',    min: 1,   unit: 'course' },
      { id: 'faa_medical',  label: 'FAA Class 3 medical',          min: 1,   unit: 'cert' },
    ],
  },
}

// ── Pricing ──────────────────────────────────────────────────────────────────

export const JUMP_PRICING = {
  tandem14k:        250,
  tandem18k:        350,    // HALO tandem (Twin Otter only)
  videoHandcam:     120,
  videoOutside:     180,
  videoCombo:       250,
  funJumperFull:    28,     // per jump — licensed jumper, full altitude
  funJumperHopNPop: 18,     // hop-n-pop (5,000 ft)
  gearRentalFull:   35,     // rig rental per jump day
  altimeterRental:  10,
  packerTip:        7,      // suggested tip per pack job
}

// ── Tandem Instructors & AFF Instructors ────────────────────────────────────

export const JUMP_INSTRUCTORS = [
  {
    id:            'ji-001',
    name:          'Tony Marchetti',
    role:          'Tandem Instructor / AFF-I',
    weightLbs:     190,
    uspaLicense:   'D-28441',
    totalJumps:    4200,
    tandemJumps:   2800,
    affJumps:      650,
    ratings:       ['Tandem Instructor', 'AFF Instructor', 'Coach'],
    manufacturer:  'UPT (Sigma)',
    medicalExpiry: daysFrom(220),
    status:        'active',
  },
  {
    id:            'ji-002',
    name:          'Brianna Voss',
    role:          'Tandem Instructor',
    weightLbs:     148,
    uspaLicense:   'D-31002',
    totalJumps:    3100,
    tandemJumps:   1950,
    affJumps:      0,
    ratings:       ['Tandem Instructor', 'Coach', 'Packer (Senior)'],
    manufacturer:  'UPT (Sigma)',
    medicalExpiry: daysFrom(160),
    status:        'active',
  },
  {
    id:            'ji-003',
    name:          'Hector Salinas',
    role:          'AFF Instructor / Coach',
    weightLbs:     175,
    uspaLicense:   'D-29550',
    totalJumps:    2600,
    tandemJumps:   0,
    affJumps:      1100,
    ratings:       ['AFF Instructor', 'Coach', 'Safety & Training Advisor'],
    manufacturer:  null,
    medicalExpiry: daysFrom(305),
    status:        'active',
  },
  {
    id:            'ji-004',
    name:          'Kyla Novak',
    role:          'Tandem Instructor / Videographer',
    weightLbs:     135,
    uspaLicense:   'D-34210',
    totalJumps:    1800,
    tandemJumps:   1100,
    affJumps:      200,
    ratings:       ['Tandem Instructor', 'AFF Instructor', 'Coach'],
    manufacturer:  'UPT (Sigma)',
    medicalExpiry: daysFrom(85),
    status:        'active',
  },
]

// ── Regular Jumpers (Licensed, Active at DZ) ────────────────────────────────

export const REGULAR_JUMPERS = [
  {
    id:           'jmp-001',
    name:         'Aaron Pollock',
    weightLbs:    195,
    exitWeight:   220,   // with gear
    uspaLicense:  'D-26110',
    licenseLevel: 'D',
    totalJumps:   1420,
    freefallHrs:  18.5,
    lastJumpDate: daysBefore(3),
    memberSince:  '2018-06-01',
    ownGear:      true,
    wingLoading:  1.35,
    canopySize:   150,
    canopyType:   'Sabre 3 150',
    disciplines:  ['Formation (4-way)', 'Freefly', 'Tracking'],
    currency:     'current',           // jumped within 30 days
    annualDues:   true,
    uspaCurrentThru: daysFrom(200),
    notes:        'Team captain — Boulder Blitz 4-way. Competition jumper.',
  },
  {
    id:           'jmp-002',
    name:         'Natalie Chen',
    weightLbs:    130,
    exitWeight:   155,
    uspaLicense:  'C-38440',
    licenseLevel: 'C',
    totalJumps:   340,
    freefallHrs:  5.8,
    lastJumpDate: daysBefore(8),
    memberSince:  '2022-03-15',
    ownGear:      true,
    wingLoading:  1.1,
    canopySize:   135,
    canopyType:   'Safire 3 135',
    disciplines:  ['Formation (4-way)', 'Wingsuit (learning)'],
    currency:     'current',
    annualDues:   true,
    uspaCurrentThru: daysFrom(180),
    notes:        'Working toward D license. 190 of 200 jump requirement met.',
  },
  {
    id:           'jmp-003',
    name:         'Jake Novotny',
    weightLbs:    215,
    exitWeight:   245,
    uspaLicense:  'B-42100',
    licenseLevel: 'B',
    totalJumps:   88,
    freefallHrs:  1.4,
    lastJumpDate: daysBefore(22),
    memberSince:  '2025-05-01',
    ownGear:      false,
    wingLoading:  null,
    canopySize:   null,
    canopyType:   'DZ rental (Navigator 260)',
    disciplines:  ['Belly (learning)'],
    currency:     'current',
    annualDues:   true,
    uspaCurrentThru: daysFrom(150),
    notes:        'Rents gear. Saving for first rig. Weekend warrior.',
  },
  {
    id:           'jmp-004',
    name:         'Leila Farzan',
    weightLbs:    118,
    exitWeight:   143,
    uspaLicense:  'D-27888',
    licenseLevel: 'D',
    totalJumps:   2100,
    freefallHrs:  28.0,
    lastJumpDate: daysBefore(1),
    memberSince:  '2016-09-01',
    ownGear:      true,
    wingLoading:  1.5,
    canopySize:   96,
    canopyType:   'Valkyrie 96',
    disciplines:  ['CRW', 'Canopy Piloting', 'Wingsuit', 'Freefly'],
    currency:     'current',
    annualDues:   true,
    uspaCurrentThru: daysFrom(240),
    notes:        'Competition canopy pilot. Regional champion 2025. Safety committee.',
  },
  {
    id:           'jmp-005',
    name:         'Marcus Bellamy',
    weightLbs:    180,
    exitWeight:   208,
    uspaLicense:  'A-48910',
    licenseLevel: 'A',
    totalJumps:   32,
    freefallHrs:  0.5,
    lastJumpDate: daysBefore(45),
    memberSince:  '2025-11-10',
    ownGear:      false,
    wingLoading:  null,
    canopySize:   null,
    canopyType:   'DZ rental (Navigator 230)',
    disciplines:  ['Belly (learning)'],
    currency:     'lapsed',            // >30 days since last jump
    annualDues:   true,
    uspaCurrentThru: daysFrom(90),
    notes:        'New A-license holder. Needs currency jump with coach before solo.',
  },
  {
    id:           'jmp-006',
    name:         'Sam Whitford',
    weightLbs:    170,
    exitWeight:   197,
    uspaLicense:  'C-36220',
    licenseLevel: 'C',
    totalJumps:   510,
    freefallHrs:  8.2,
    lastJumpDate: daysBefore(5),
    memberSince:  '2020-04-01',
    ownGear:      true,
    wingLoading:  1.25,
    canopySize:   150,
    canopyType:   'Pilot 150',
    disciplines:  ['Freefly', 'Angle Flying', 'Tracking'],
    currency:     'current',
    annualDues:   true,
    uspaCurrentThru: daysFrom(210),
    notes:        'Freefly organizer. Coaches newer jumpers informally.',
  },
  {
    id:           'jmp-007',
    name:         'Tracy Okafor',
    weightLbs:    158,
    exitWeight:   185,
    uspaLicense:  'B-44600',
    licenseLevel: 'B',
    totalJumps:   72,
    freefallHrs:  1.1,
    lastJumpDate: daysBefore(12),
    memberSince:  '2025-08-20',
    ownGear:      false,
    wingLoading:  null,
    canopySize:   null,
    canopyType:   'DZ rental (Pilot 190)',
    disciplines:  ['Belly', 'Tracking (learning)'],
    currency:     'current',
    annualDues:   true,
    uspaCurrentThru: daysFrom(120),
    notes:        'Just bought a used rig — awaiting rigger inspection before first use.',
  },
]

// ── Prospects (Expressed Interest / First-time / Not Yet Licensed) ──────────

export const PROSPECTS = [
  {
    id:           'prsp-001',
    name:         'Jordan Whitaker',
    weightLbs:    175,
    email:        'jwhitaker@email.com',
    phone:        '720-555-0311',
    interest:     'tandem',
    source:       'Website inquiry',
    dateInquired: daysBefore(5),
    notes:        'Birthday gift — wants to jump in April. Asked about video package.',
    status:       'scheduled',
    scheduledDate:daysFrom(10),
    completedTandems: 0,
    convertToAFF: null,
  },
  {
    id:           'prsp-002',
    name:         'Michelle Park',
    weightLbs:    140,
    email:        'mpark@email.com',
    phone:        '303-555-0422',
    interest:     'aff',
    source:       'Tandem follow-up',
    dateInquired: daysBefore(12),
    notes:        'Did tandem last season — loved it. Wants to start AFF this spring.',
    status:       'contacted',
    scheduledDate:null,
    completedTandems: 1,
    convertToAFF: true,
  },
  {
    id:           'prsp-003',
    name:         'Brian Gunderson',
    weightLbs:    225,
    email:        'bgunderson@email.com',
    phone:        '720-555-0188',
    interest:     'tandem',
    source:       'Groupon / Voucher',
    dateInquired: daysBefore(30),
    notes:        'Purchased voucher. Close to weight limit — confirm at check-in. Expires June 30.',
    status:       'voucher_redeemed',
    scheduledDate:null,
    completedTandems: 0,
    convertToAFF: null,
  },
  {
    id:           'prsp-004',
    name:         'Aisha Okoye',
    weightLbs:    135,
    email:        'aokoye@email.com',
    phone:        '303-555-0577',
    interest:     'static_line',
    source:       'Friend referral (Aaron Pollock)',
    dateInquired: daysBefore(8),
    notes:        'Referred by regular jumper. Interested in cheapest path to A-license.',
    status:       'contacted',
    scheduledDate:null,
    completedTandems: 0,
    convertToAFF: null,
  },
  {
    id:           'prsp-005',
    name:         'Carlos Medina',
    weightLbs:    190,
    email:        'cmedina@email.com',
    phone:        '720-555-0699',
    interest:     'tandem',
    source:       'Walk-in',
    dateInquired: daysBefore(2),
    notes:        'Stopped by the DZ Saturday. Watching jumpers land. Very enthusiastic. Left contact info.',
    status:       'new_lead',
    scheduledDate:null,
    completedTandems: 0,
    convertToAFF: null,
  },
  {
    id:           'prsp-006',
    name:         'Hannah Liu',
    weightLbs:    125,
    email:        'hliu@email.com',
    phone:        '303-555-0833',
    interest:     'aff',
    source:       'Instagram DM',
    dateInquired: daysBefore(18),
    notes:        'Former gymnast. Did 3 tandems at other DZs. Wants to start training here.',
    status:       'contacted',
    scheduledDate:null,
    completedTandems: 3,
    convertToAFF: true,
  },
]

// ── AFF Students (In-Progress) ───────────────────────────────────────────────

export const AFF_STUDENTS = [
  {
    id:             'affs-001',
    name:           'Derek Yamashita',
    weightLbs:      168,
    exitWeight:     195,
    email:          'dyamashita@email.com',
    phone:          '720-555-0401',
    enrolledDate:   '2026-02-01',
    program:        'aff',
    currentLevel:   5,
    status:         'active',
    assignedInstructorId: 'ji-003',  // Hector Salinas (AFF-I)
    totalJumps:     12,
    freefallTime:   0.18,
    groundSchoolComplete: true,
    docs: {
      governmentId:  { type: 'drivers_license', expiry: '2029-05-20', uploaded: true },
      uspaMembership:{ number: 'TMP-88421', expiry: daysFrom(60), uploaded: true },
      medicalWaiver: { signed: true, signedDate: '2026-02-01' },
    },
    levelHistory: [
      { level: 1, date: '2026-02-08', result: 'pass', instructor: 'ji-003', notes: 'Solid arch, good awareness' },
      { level: 2, date: '2026-02-15', result: 'pass', instructor: 'ji-003', notes: 'Practice pulls clean' },
      { level: 3, date: '2026-02-22', result: 'repeat', instructor: 'ji-003', notes: 'Unstable exit — repeat level' },
      { level: 3, date: '2026-02-23', result: 'pass', instructor: 'ji-001', notes: 'Clean exit, good heading' },
      { level: 4, date: '2026-03-01', result: 'pass', instructor: 'ji-003', notes: '360 turns both directions' },
      { level: 5, date: '2026-03-15', result: 'pass', instructor: 'ji-003', notes: 'Forward movement good' },
    ],
    notes: 'Progressing well. Needs 13 more jumps + requirements for A-license.',
  },
  {
    id:             'affs-002',
    name:           'Olivia Tran',
    weightLbs:      122,
    exitWeight:     150,
    email:          'otran@email.com',
    phone:          '303-555-0512',
    enrolledDate:   '2026-03-01',
    program:        'aff',
    currentLevel:   2,
    status:         'active',
    assignedInstructorId: 'ji-001',  // Tony Marchetti (AFF-I)
    totalJumps:     3,
    freefallTime:   0.05,
    groundSchoolComplete: true,
    docs: {
      governmentId:  { type: 'passport', expiry: '2031-11-10', uploaded: true },
      uspaMembership:{ number: 'TMP-89102', expiry: daysFrom(55), uploaded: true },
      medicalWaiver: { signed: true, signedDate: '2026-03-01' },
    },
    levelHistory: [
      { level: 1, date: '2026-03-08', result: 'pass', instructor: 'ji-001', notes: 'Excellent body position' },
      { level: 2, date: '2026-03-15', result: 'pass', instructor: 'ji-001', notes: 'Smooth practice pulls' },
    ],
    notes: 'Natural talent. Former gymnast — great body awareness.',
  },
  {
    id:             'affs-003',
    name:           'Ryan Kowalski',
    weightLbs:      200,
    exitWeight:     228,
    email:          'rkowalski@email.com',
    phone:          '720-555-0655',
    enrolledDate:   '2025-10-01',
    program:        'aff',
    currentLevel:   7,
    status:         'active',
    assignedInstructorId: 'ji-003',
    totalJumps:     22,
    freefallTime:   0.35,
    groundSchoolComplete: true,
    docs: {
      governmentId:  { type: 'drivers_license', expiry: '2028-08-01', uploaded: true },
      uspaMembership:{ number: 'TMP-84330', expiry: daysFrom(30), uploaded: true },
      medicalWaiver: { signed: true, signedDate: '2025-10-01' },
    },
    levelHistory: [
      { level: 1, date: '2025-10-11', result: 'pass', instructor: 'ji-003', notes: '' },
      { level: 2, date: '2025-10-18', result: 'pass', instructor: 'ji-003', notes: '' },
      { level: 3, date: '2025-10-25', result: 'pass', instructor: 'ji-003', notes: '' },
      { level: 4, date: '2025-11-01', result: 'repeat', instructor: 'ji-003', notes: 'Heading drift on turns' },
      { level: 4, date: '2025-11-08', result: 'pass', instructor: 'ji-001', notes: '' },
      { level: 5, date: '2025-11-22', result: 'pass', instructor: 'ji-003', notes: '' },
      { level: 6, date: '2025-12-06', result: 'repeat', instructor: 'ji-003', notes: 'Barrel roll incomplete' },
      { level: 6, date: '2025-12-13', result: 'pass', instructor: 'ji-003', notes: '' },
      { level: 7, date: '2026-03-22', result: 'pass', instructor: 'ji-003', notes: 'Hop-n-pop clean. Ready for self-supervised jumps.' },
    ],
    notes: 'AFF complete! Needs 3 more self-supervised jumps + A-license requirements. USPA membership expiring soon — remind to renew.',
  },
]

// ── Safety / Weather Limits ─────────────────────────────────────────────────

export const DZ_WEATHER_LIMITS = {
  maxWindStudent:      14,    // knots — ground wind limit for students
  maxWindLicensed:     25,    // knots — ground wind for licensed jumpers
  maxWindTandem:       18,    // knots — ground wind for tandems
  maxUpperWinds:       40,    // knots at altitude
  minCeiling:          3500,  // ft AGL — must see ground from exit alt
  minVisibility:       3,     // statute miles
  lightningHold:       30,    // minutes after last strike
}

// ── Mock Jump Flights (common flight object with jumpInfo) ──────────────────
//
// jumpInfo shape:
//   jumpAltitudeFt   — exit altitude AGL
//   jumpType         — 'tandem' | 'fun_jump' | 'aff' | 'hop_n_pop' | 'formation'
//   jumpMasterId     — instructor / jump-master id (optional for fun jumps)
//   jumpMasterName   — display name
//   manifest[]       — array of { jumperId, name, weightLbs, exitWeight, licenseLevel, slot }
//   loadNumber       — load # for the day
//   airport          — DZ airport id

const now = Date.now()
const h = (n) => new Date(now + n * 3_600_000).toISOString()

export const mockJumpFlights = [
  // ── Load 1: Tandem load — Grand Caravan ─────────────────────────────────────
  {
    id:                  'jf-001',
    callsign:            'N208JB',
    tailNumber:          'N208JB',
    aircraftType:        'C208B',
    departure:           'KBDU',
    arrival:             'KBDU',
    airport:             'KBDU',
    plannedDepartureUtc: h(0.5),
    plannedArrivalUtc:   h(0.8),
    status:              'planned',
    pic:                 'Hennessy, R.',
    picId:               'jp-pil-001',
    sic:                 null,
    sicId:               null,
    passengers:          12,
    missionType:         'parachute_ops',
    part:                '91',
    part91Type:          'parachute_ops',
    riskScore:           28,
    riskSnapshot: {
      capturedAt:      h(-0.1),
      lastCheckedAt:   h(-0.1),
      ratioToBaseline: 1.10,
      riskTrend:       'stable',
      riskDelta:       0,
      weatherSummary:  { flightCategory: 'VFR', sigmetCount: 0, airmetCount: 0, windKts: 8, visibilitySm: 10 },
      terrainProfile:  null,
      riskItems: [
        { id: 'op_para_ops', label: 'Parachute operations — §105', category: 'operational', severity: 'low' },
      ],
    },
    jumpInfo: {
      jumpAltitudeFt:  14000,
      jumpType:        'tandem',
      jumpMasterId:    'ji-001',
      jumpMasterName:  'Tony Marchetti',
      loadNumber:      1,
      airport:         'KBDU',
      manifest: [
        { jumperId: 'ji-001',   name: 'Tony Marchetti',   weightLbs: 190, exitWeight: 220, licenseLevel: 'TI', slot: 'tandem-instructor' },
        { jumperId: 'prsp-001', name: 'Jordan Whitaker',  weightLbs: 175, exitWeight: 175, licenseLevel: '--', slot: 'tandem-student' },
        { jumperId: 'ji-002',   name: 'Brianna Voss',     weightLbs: 148, exitWeight: 178, licenseLevel: 'TI', slot: 'tandem-instructor' },
        { jumperId: 'prsp-T1',  name: 'Walk-in Guest #1', weightLbs: 165, exitWeight: 165, licenseLevel: '--', slot: 'tandem-student' },
        { jumperId: 'ji-004',   name: 'Kyla Novak',       weightLbs: 135, exitWeight: 165, licenseLevel: 'TI', slot: 'tandem-instructor' },
        { jumperId: 'prsp-T2',  name: 'Walk-in Guest #2', weightLbs: 150, exitWeight: 150, licenseLevel: '--', slot: 'tandem-student' },
        { jumperId: 'jmp-001',  name: 'Aaron Pollock',    weightLbs: 195, exitWeight: 220, licenseLevel: 'D',  slot: 'videographer' },
        { jumperId: 'jmp-004',  name: 'Leila Farzan',     weightLbs: 118, exitWeight: 143, licenseLevel: 'D',  slot: 'videographer' },
        { jumperId: 'jmp-002',  name: 'Natalie Chen',     weightLbs: 130, exitWeight: 155, licenseLevel: 'C',  slot: 'fun-jumper' },
        { jumperId: 'jmp-006',  name: 'Sam Whitford',     weightLbs: 170, exitWeight: 197, licenseLevel: 'C',  slot: 'fun-jumper' },
      ],
    },
  },

  // ── Load 2: AFF + fun jumpers — Grand Caravan ──────────────────────────────
  {
    id:                  'jf-002',
    callsign:            'N208JB',
    tailNumber:          'N208JB',
    aircraftType:        'C208B',
    departure:           'KBDU',
    arrival:             'KBDU',
    airport:             'KBDU',
    plannedDepartureUtc: h(1.2),
    plannedArrivalUtc:   h(1.5),
    status:              'planned',
    pic:                 'Torres, M.',
    picId:               'jp-pil-002',
    sic:                 null,
    sicId:               null,
    passengers:          9,
    missionType:         'parachute_ops',
    part:                '91',
    part91Type:          'parachute_ops',
    riskScore:           32,
    riskSnapshot: {
      capturedAt:      h(-0.1),
      lastCheckedAt:   h(-0.1),
      ratioToBaseline: 1.15,
      riskTrend:       'stable',
      riskDelta:       0,
      weatherSummary:  { flightCategory: 'VFR', sigmetCount: 0, airmetCount: 0, windKts: 10, visibilitySm: 10 },
      terrainProfile:  null,
      riskItems: [
        { id: 'op_para_ops', label: 'Parachute operations — §105', category: 'operational', severity: 'low' },
        { id: 'op_aff_student', label: 'AFF student on board — additional supervision required', category: 'operational', severity: 'moderate' },
      ],
    },
    jumpInfo: {
      jumpAltitudeFt:  14000,
      jumpType:        'aff',
      jumpMasterId:    'ji-003',
      jumpMasterName:  'Hector Salinas',
      loadNumber:      2,
      airport:         'KBDU',
      manifest: [
        { jumperId: 'ji-003',   name: 'Hector Salinas',   weightLbs: 175, exitWeight: 202, licenseLevel: 'AFF-I', slot: 'aff-instructor' },
        { jumperId: 'ji-001',   name: 'Tony Marchetti',   weightLbs: 190, exitWeight: 220, licenseLevel: 'AFF-I', slot: 'aff-instructor' },
        { jumperId: 'affs-001', name: 'Derek Yamashita',  weightLbs: 168, exitWeight: 195, licenseLevel: 'STU',   slot: 'aff-student' },
        { jumperId: 'jmp-001',  name: 'Aaron Pollock',    weightLbs: 195, exitWeight: 220, licenseLevel: 'D',     slot: 'fun-jumper' },
        { jumperId: 'jmp-004',  name: 'Leila Farzan',     weightLbs: 118, exitWeight: 143, licenseLevel: 'D',     slot: 'fun-jumper' },
        { jumperId: 'jmp-006',  name: 'Sam Whitford',     weightLbs: 170, exitWeight: 197, licenseLevel: 'C',     slot: 'fun-jumper' },
        { jumperId: 'jmp-002',  name: 'Natalie Chen',     weightLbs: 130, exitWeight: 155, licenseLevel: 'C',     slot: 'fun-jumper' },
        { jumperId: 'jmp-007',  name: 'Tracy Okafor',     weightLbs: 158, exitWeight: 185, licenseLevel: 'B',     slot: 'fun-jumper' },
        { jumperId: 'jmp-003',  name: 'Jake Novotny',     weightLbs: 215, exitWeight: 245, licenseLevel: 'B',     slot: 'fun-jumper' },
      ],
    },
  },

  // ── Load 3: Formation dive — Twin Otter (big plane, big group) ─────────────
  {
    id:                  'jf-003',
    callsign:            'N406DZ',
    tailNumber:          'N406DZ',
    aircraftType:        'DHC6',
    departure:           'KBDU',
    arrival:             'KBDU',
    airport:             'KBDU',
    plannedDepartureUtc: h(1.8),
    plannedArrivalUtc:   h(2.1),
    status:              'planned',
    pic:                 'Briggs, C.',
    picId:               'jp-pil-003',
    sic:                 null,
    sicId:               null,
    passengers:          16,
    missionType:         'parachute_ops',
    part:                '91',
    part91Type:          'parachute_ops',
    riskScore:           30,
    riskSnapshot: {
      capturedAt:      h(-0.1),
      lastCheckedAt:   h(-0.1),
      ratioToBaseline: 1.08,
      riskTrend:       'stable',
      riskDelta:       0,
      weatherSummary:  { flightCategory: 'VFR', sigmetCount: 0, airmetCount: 0, windKts: 8, visibilitySm: 10 },
      terrainProfile:  null,
      riskItems: [
        { id: 'op_para_ops', label: 'Parachute operations — §105', category: 'operational', severity: 'low' },
        { id: 'op_formation', label: 'Formation skydive — multiple exit groups', category: 'operational', severity: 'moderate' },
      ],
    },
    jumpInfo: {
      jumpAltitudeFt:  14000,
      jumpType:        'formation',
      jumpMasterId:    'jmp-001',
      jumpMasterName:  'Aaron Pollock',
      loadNumber:      3,
      airport:         'KBDU',
      manifest: [
        { jumperId: 'jmp-001',  name: 'Aaron Pollock',    weightLbs: 195, exitWeight: 220, licenseLevel: 'D',     slot: 'organizer' },
        { jumperId: 'jmp-004',  name: 'Leila Farzan',     weightLbs: 118, exitWeight: 143, licenseLevel: 'D',     slot: 'fun-jumper' },
        { jumperId: 'jmp-006',  name: 'Sam Whitford',     weightLbs: 170, exitWeight: 197, licenseLevel: 'C',     slot: 'fun-jumper' },
        { jumperId: 'jmp-002',  name: 'Natalie Chen',     weightLbs: 130, exitWeight: 155, licenseLevel: 'C',     slot: 'fun-jumper' },
        { jumperId: 'ji-001',   name: 'Tony Marchetti',   weightLbs: 190, exitWeight: 220, licenseLevel: 'D',     slot: 'fun-jumper' },
        { jumperId: 'ji-003',   name: 'Hector Salinas',   weightLbs: 175, exitWeight: 202, licenseLevel: 'D',     slot: 'fun-jumper' },
        { jumperId: 'ji-004',   name: 'Kyla Novak',       weightLbs: 135, exitWeight: 165, licenseLevel: 'D',     slot: 'fun-jumper' },
        { jumperId: 'jmp-007',  name: 'Tracy Okafor',     weightLbs: 158, exitWeight: 185, licenseLevel: 'B',     slot: 'fun-jumper' },
        { jumperId: 'ji-002',   name: 'Brianna Voss',     weightLbs: 148, exitWeight: 178, licenseLevel: 'D',     slot: 'fun-jumper' },
        { jumperId: 'affs-003', name: 'Ryan Kowalski',    weightLbs: 200, exitWeight: 228, licenseLevel: 'STU',   slot: 'fun-jumper' },
      ],
    },
  },

  // ── Load 4: Hop-n-pop — C182 (small load, low altitude) ───────────────────
  {
    id:                  'jf-004',
    callsign:            'N182JK',
    tailNumber:          'N182JK',
    aircraftType:        'C182',
    departure:           'KBDU',
    arrival:             'KBDU',
    airport:             'KBDU',
    plannedDepartureUtc: h(2.5),
    plannedArrivalUtc:   h(2.7),
    status:              'planned',
    pic:                 'Kowalski, D.',
    picId:               'jp-pil-004',
    sic:                 null,
    sicId:               null,
    passengers:          3,
    missionType:         'parachute_ops',
    part:                '91',
    part91Type:          'parachute_ops',
    riskScore:           20,
    riskSnapshot: {
      capturedAt:      h(-0.1),
      lastCheckedAt:   h(-0.1),
      ratioToBaseline: 0.95,
      riskTrend:       'stable',
      riskDelta:       0,
      weatherSummary:  { flightCategory: 'VFR', sigmetCount: 0, airmetCount: 0, windKts: 6, visibilitySm: 10 },
      terrainProfile:  null,
      riskItems: [
        { id: 'op_para_ops', label: 'Parachute operations — §105', category: 'operational', severity: 'low' },
      ],
    },
    jumpInfo: {
      jumpAltitudeFt:  5000,
      jumpType:        'hop_n_pop',
      jumpMasterId:    null,
      jumpMasterName:  null,
      loadNumber:      4,
      airport:         'KBDU',
      manifest: [
        { jumperId: 'jmp-004',  name: 'Leila Farzan',   weightLbs: 118, exitWeight: 143, licenseLevel: 'D', slot: 'fun-jumper' },
        { jumperId: 'jmp-001',  name: 'Aaron Pollock',  weightLbs: 195, exitWeight: 220, licenseLevel: 'D', slot: 'fun-jumper' },
        { jumperId: 'jmp-006',  name: 'Sam Whitford',   weightLbs: 170, exitWeight: 197, licenseLevel: 'C', slot: 'fun-jumper' },
      ],
    },
  },

  // ── Load 5: Morning tandem completed ──────────────────────────────────────
  {
    id:                  'jf-005',
    callsign:            'N208JB',
    tailNumber:          'N208JB',
    aircraftType:        'C208B',
    departure:           'KBDU',
    arrival:             'KBDU',
    airport:             'KBDU',
    plannedDepartureUtc: h(-1.5),
    plannedArrivalUtc:   h(-1.2),
    status:              'completed',
    pic:                 'Hennessy, R.',
    picId:               'jp-pil-001',
    sic:                 null,
    sicId:               null,
    passengers:          10,
    missionType:         'parachute_ops',
    part:                '91',
    part91Type:          'parachute_ops',
    riskScore:           25,
    riskSnapshot: {
      capturedAt:      h(-1.6),
      lastCheckedAt:   h(-1.6),
      ratioToBaseline: 1.05,
      riskTrend:       'stable',
      riskDelta:       0,
      weatherSummary:  { flightCategory: 'VFR', sigmetCount: 0, airmetCount: 0, windKts: 5, visibilitySm: 10 },
      terrainProfile:  null,
      riskItems: [
        { id: 'op_para_ops', label: 'Parachute operations — §105', category: 'operational', severity: 'low' },
      ],
    },
    jumpInfo: {
      jumpAltitudeFt:  14000,
      jumpType:        'tandem',
      jumpMasterId:    'ji-002',
      jumpMasterName:  'Brianna Voss',
      loadNumber:      0,
      airport:         'KBDU',
      manifest: [
        { jumperId: 'ji-002',   name: 'Brianna Voss',     weightLbs: 148, exitWeight: 178, licenseLevel: 'TI', slot: 'tandem-instructor' },
        { jumperId: 'prsp-T3',  name: 'Morning Guest #1', weightLbs: 185, exitWeight: 185, licenseLevel: '--', slot: 'tandem-student' },
        { jumperId: 'ji-001',   name: 'Tony Marchetti',   weightLbs: 190, exitWeight: 220, licenseLevel: 'TI', slot: 'tandem-instructor' },
        { jumperId: 'prsp-T4',  name: 'Morning Guest #2', weightLbs: 145, exitWeight: 145, licenseLevel: '--', slot: 'tandem-student' },
        { jumperId: 'ji-004',   name: 'Kyla Novak',       weightLbs: 135, exitWeight: 165, licenseLevel: 'TI', slot: 'tandem-instructor' },
        { jumperId: 'prsp-T5',  name: 'Morning Guest #3', weightLbs: 160, exitWeight: 160, licenseLevel: '--', slot: 'tandem-student' },
        { jumperId: 'jmp-001',  name: 'Aaron Pollock',    weightLbs: 195, exitWeight: 220, licenseLevel: 'D',  slot: 'videographer' },
        { jumperId: 'jmp-002',  name: 'Natalie Chen',     weightLbs: 130, exitWeight: 155, licenseLevel: 'C',  slot: 'videographer' },
        { jumperId: 'jmp-004',  name: 'Leila Farzan',     weightLbs: 118, exitWeight: 143, licenseLevel: 'D',  slot: 'fun-jumper' },
        { jumperId: 'jmp-006',  name: 'Sam Whitford',     weightLbs: 170, exitWeight: 197, licenseLevel: 'C',  slot: 'fun-jumper' },
      ],
    },
  },
]

// ── Load Manifest Helper ────────────────────────────────────────────────────

export function getTodayLoads() {
  const hour = new Date().getHours()
  const isOperating = hour >= 8 && hour < 18
  const loadsToday = isOperating ? 4 + Math.floor(Math.random() * 6) : 0
  const currentLoad = isOperating ? Math.ceil(loadsToday * ((hour - 8) / 10)) : 0
  return {
    isOperating,
    loadsFlown:     currentLoad,
    loadsPlanned:   loadsToday,
    jumpersToday:   currentLoad * 12,
    tandemsToday:   Math.floor(currentLoad * 2.5),
    nextLoadEta:    isOperating ? `${8 + Math.floor(Math.random() * 15)} min` : '--',
    planesFlying:   isOperating ? (hour < 12 ? 2 : 1) : 0,
    planesTotal:    JUMP_PLANES.filter(p => p.status === 'airworthy').length,
    windGround:     isOperating ? `${5 + Math.floor(Math.random() * 12)} kt` : '--',
    windAltitude:   isOperating ? `${15 + Math.floor(Math.random() * 20)} kt` : '--',
    jumpRun:        isOperating ? `${220 + Math.floor(Math.random() * 50)}°` : '--',
  }
}
