// ─────────────────────────────────────────────────────────────────
// Journeys Aviation, Inc. — Boulder Municipal Airport (KBDU)
// FBO · Flight School · Aircraft Rental · Aircraft Maintenance
// Sources: journeysaviation.com, 2023-24 Rental Price List PDF,
//          FlightAware, AirNav, AOPA, about-us page
// NOTE: Mile High Gliding is a SEPARATE company — see mhgData.js
// ─────────────────────────────────────────────────────────────────

export const JB_INFO = {
  name: 'Journeys Aviation',
  legalName: 'Journeys Aviation, Inc.',
  tagline: 'Flight School · FBO · Aircraft Rental',
  address: '3335 Airport Rd, Suite A, Boulder, CO 80301',
  airport: 'Boulder Municipal Airport (KBDU)',
  phone: '(303) 449-4210',
  maintenancePhone: '(720) 620-0033',
  email: 'boulderdesk@journeysaviation.com',
  website: 'https://www.journeysaviation.com',
  facebook: 'https://www.facebook.com/JourneysAviation/',
  yelp: 'https://www.yelp.com/biz/journeys-aviation-boulder',
  aopa: 'https://www.aopa.org/destinations/business/29676',
  airnav: 'http://www.airnav.com/airport/KBDU/JOURNEYS_AV',
  linkedin: 'https://www.linkedin.com/company/journeys-aviation-inc',
  founded: 2019,
  radioFreq: '122.725',
  hours: 'Daily · 8 AM – 5 PM',
  eaaChapter: 'EAA Chapter 1627 (Boulder)',
  metarUrl: 'https://aviationweather.gov/data/metar/?id=KBDU&hours=6',
  webcamUrl: 'https://weathercams.faa.gov/map/-105.22583,39.8594,10/airport/BDU/details/weather',
  windyUrl: 'https://www.windy.com/airport/KBDU',
  mission: 'Provide a rewarding first class experience to all who visit Boulder Airport, and inspire the next generation of aviators.',
  // Ground transport note from FBO page
  groundTransport: 'City of Boulder does not provide courtesy car. Uber recommended.',
}

/* ──────────────── STAFF (from about-us page) ──────────────── */
export const JB_STAFF = [
  {
    name: 'Andrew McKenna',
    role: 'President & CEO / Co-Founder',
    bio: 'Co-founded Journeys Aviation in 2019. Commercial, single & multi-engine land, instrument rated. ~1,000 flight hours. Lt. Colonel, Civil Air Patrol (airborne SAR). Founded EAA Chapter 1627; president 2019–2023. Board member, International Group for Historic Aircraft Recovery — six expeditions investigating Amelia Earhart\'s disappearance. Member of The Explorers Club since 2007.',
  },
  {
    name: 'Scott Griffith',
    role: 'Assistant Manager / AGI / IGI',
    bio: 'Private pilot. Advanced Ground Instructor & Instrument Ground Instructor. Retired after 30 years teaching with Boulder Valley School District. Coordinates Young Eagles program with EAA Chapter 1627.',
  },
  {
    name: 'Tess Kim',
    role: 'Accounting',
    bio: 'Financial management and operations.',
  },
]

/* ──────────────── AIRCRAFT FLEET ────────────────
   Every aircraft from the 2023-24 Rental Price List (Dec 1, 2023).
   W&B data from type-certificate / POH typical values.
   Actual aircraft empty weights vary — consult POH for the specific tail. */

export const JB_FLEET = [
  {
    id: 'n6316s',
    tailNumber: 'N6316S',
    type: 'Cessna 150G',
    year: 1966,
    category: 'trainer',
    seats: 2,
    engine: 'Continental O-200-A · 100 hp (converted 150 hp)',
    fuelCapacity: '22.5 gal usable (26 gal total)',
    // W&B — type-cert typical; actual per POH
    emptyWeight: 1091,
    maxGross: 1600,
    usefulLoad: 509,
    fuelWeight: 135,        // 22.5 gal × 6 lbs
    payloadWithFuel: 374,   // useful load - fuel
    cg: { fwd: 28.0, aft: 36.0, datum: 'firewall' },
    stations: [
      { name: 'Front Seats', arm: 39.0, maxWeight: 340 },
      { name: 'Fuel (22.5 gal)', arm: 42.0, maxWeight: 135 },
      { name: 'Baggage', arm: 64.0, maxWeight: 120 },
    ],
    avionics: 'Garmin 175 GPS, Dual Nav/Com, Dual G5, Lynx 9000 ADS-B In/Out',
    rates: { member: 139, prepay: 134.83, nonMember: 159 },
    rateUnit: 'Hobbs hr (wet)',
    soloInsurance: 'Student',
    status: 'airworthy',
    role: 'Primary trainer',
    notes: 'Upgraded 150 hp engine. Classic trainer, economical, light and responsive.',
  },
  {
    id: 'n235nd',
    tailNumber: 'N235ND',
    type: 'Diamond DA20-C1 Eclipse',
    year: null,
    category: 'trainer',
    seats: 2,
    engine: 'Continental IO-240-B · 125 hp',
    fuelCapacity: '24 gal usable',
    emptyWeight: 1168,
    maxGross: 1764,
    usefulLoad: 596,
    fuelWeight: 144,        // 24 gal × 6 lbs
    payloadWithFuel: 452,
    cg: { fwd: 8.07, aft: 12.16, datum: 'reference datum' },
    stations: [
      { name: 'Occupants (side-by-side)', arm: 10.0, maxWeight: 397 },
      { name: 'Fuel (24 gal)', arm: 11.8, maxWeight: 144 },
      { name: 'Baggage', arm: 18.9, maxWeight: 44 },
    ],
    avionics: 'Garmin 375 GPS, Aspen E5, ADS-B Out — VFR ONLY',
    rates: { member: 145, prepay: 140.65, nonMember: 165 },
    rateUnit: 'Hobbs hr (wet)',
    soloInsurance: 'Student',
    status: 'airworthy',
    role: 'Primary trainer · VFR only',
    notes: 'Low-wing composite. Stick control. Excellent visibility. VFR only.',
  },
  {
    id: 'n641dc',
    tailNumber: 'N641DC',
    type: 'Diamond DA20-C1 Eclipse',
    year: null,
    category: 'trainer',
    seats: 2,
    engine: 'Continental IO-240-B · 125 hp',
    fuelCapacity: '24 gal usable',
    emptyWeight: 1168,
    maxGross: 1764,
    usefulLoad: 596,
    fuelWeight: 144,
    payloadWithFuel: 452,
    cg: { fwd: 8.07, aft: 12.16, datum: 'reference datum' },
    stations: [
      { name: 'Occupants (side-by-side)', arm: 10.0, maxWeight: 397 },
      { name: 'Fuel (24 gal)', arm: 11.8, maxWeight: 144 },
      { name: 'Baggage', arm: 18.9, maxWeight: 44 },
    ],
    avionics: 'Garmin 650, Dual GF, Dual NavCom, ADS-B In/Out',
    rates: { member: 149, prepay: 144.53, nonMember: 169 },
    rateUnit: 'Hobbs hr (wet)',
    soloInsurance: 'Student',
    status: 'airworthy',
    role: 'Primary trainer · IFR capable',
    notes: 'IFR-equipped Diamond. Stick control. Great for instrument approach practice.',
  },
  {
    id: 'n52993',
    tailNumber: 'N52993',
    type: 'Cessna 172P Skyhawk',
    year: null,
    category: 'trainer',
    seats: 4,
    engine: 'Lycoming O-320-D2J · 160 hp',
    fuelCapacity: '43 gal usable (standard tanks)',
    emptyWeight: 1420,
    maxGross: 2400,
    usefulLoad: 980,
    fuelWeight: 258,        // 43 gal × 6 lbs
    payloadWithFuel: 722,
    cg: { fwd: 35.0, aft: 47.3, datum: 'firewall' },
    stations: [
      { name: 'Front Seats', arm: 37.0, maxWeight: 400 },
      { name: 'Rear Seats', arm: 73.0, maxWeight: 340 },
      { name: 'Fuel (43 gal)', arm: 46.0, maxWeight: 258 },
      { name: 'Baggage A', arm: 95.0, maxWeight: 120 },
    ],
    avionics: 'Garmin Aera 660, GTX 327 ADS-B In/Out',
    rates: { member: 145, prepay: 140.65, nonMember: 165 },
    rateUnit: 'Hobbs hr (wet)',
    soloInsurance: 'Student',
    status: 'airworthy',
    role: 'Primary trainer · Cross-country',
    notes: '4-seat workhorse. Standard 160 hp. Reliable IFR/VFR platform.',
  },
  {
    id: 'n733jm',
    tailNumber: 'N733JM',
    type: 'Cessna 172N Skyhawk (180 hp)',
    year: null,
    category: 'trainer',
    seats: 4,
    engine: 'Lycoming O-360 · 180 hp conversion',
    fuelCapacity: '43 gal usable',
    emptyWeight: 1450,
    maxGross: 2450,
    usefulLoad: 1000,
    fuelWeight: 258,
    payloadWithFuel: 742,
    cg: { fwd: 35.0, aft: 47.3, datum: 'firewall' },
    stations: [
      { name: 'Front Seats', arm: 37.0, maxWeight: 400 },
      { name: 'Rear Seats', arm: 73.0, maxWeight: 340 },
      { name: 'Fuel (43 gal)', arm: 46.0, maxWeight: 258 },
      { name: 'Baggage A', arm: 95.0, maxWeight: 120 },
    ],
    avionics: 'Garmin 650, Dual G5s, Stratus ADS-B In/Out, S-Tec 2-Axis AP',
    rates: { member: 159, prepay: 154.23, nonMember: 179 },
    rateUnit: 'Hobbs hr (wet)',
    soloInsurance: 'Student',
    status: 'airworthy',
    role: 'Training · IFR · Cross-country · Autopilot',
    notes: '180 hp conversion. 2-axis autopilot. Best-equipped 172 in fleet. Great for mountain flying.',
  },
  {
    id: 'n333rx',
    tailNumber: 'N333RX',
    type: 'Cessna 172G Skyhawk (180 hp)',
    year: null,
    category: 'trainer',
    seats: 4,
    engine: 'Lycoming O-360 · 180 hp conversion',
    fuelCapacity: '39 gal usable',
    emptyWeight: 1375,
    maxGross: 2300,
    usefulLoad: 925,
    fuelWeight: 234,        // 39 gal × 6 lbs
    payloadWithFuel: 691,
    cg: { fwd: 35.0, aft: 47.3, datum: 'firewall' },
    stations: [
      { name: 'Front Seats', arm: 37.0, maxWeight: 400 },
      { name: 'Rear Seats', arm: 73.0, maxWeight: 340 },
      { name: 'Fuel (39 gal)', arm: 46.0, maxWeight: 234 },
      { name: 'Baggage A', arm: 95.0, maxWeight: 120 },
    ],
    avionics: 'Garmin 430 GPS, ADS-B In/Out',
    rates: { member: 145, prepay: 140.65, nonMember: 165 },
    rateUnit: 'Hobbs hr (wet)',
    soloInsurance: 'Student',
    status: 'airworthy',
    role: 'Training · Cross-country',
    notes: '180 hp conversion. Older airframe, lower cost, great performance at altitude.',
  },
  {
    id: 'n6694e',
    tailNumber: 'N6694E',
    type: 'Cessna 172N Skyhawk',
    year: null,
    category: 'trainer',
    seats: 4,
    engine: 'Lycoming O-320-H2AD · 160 hp',
    fuelCapacity: '43 gal usable',
    emptyWeight: 1450,
    maxGross: 2300,
    usefulLoad: 850,
    fuelWeight: 258,
    payloadWithFuel: 592,
    cg: { fwd: 35.0, aft: 47.3, datum: 'firewall' },
    stations: [
      { name: 'Front Seats', arm: 37.0, maxWeight: 400 },
      { name: 'Rear Seats', arm: 73.0, maxWeight: 340 },
      { name: 'Fuel (43 gal)', arm: 46.0, maxWeight: 258 },
      { name: 'Baggage A', arm: 95.0, maxWeight: 120 },
    ],
    avionics: 'Garmin 430W, Dual Garmin G5, Stratus ADS-B In/Out',
    rates: { member: 161, prepay: 156.17, nonMember: 181 },
    rateUnit: 'Hobbs hr (wet)',
    soloInsurance: 'Student',
    status: 'airworthy',
    role: 'Training · IFR · Cross-country',
    notes: 'WAAS-capable GPS. Dual G5 glass panel. Standard 160 hp.',
  },
  {
    id: 'n3547l',
    tailNumber: 'N3547L',
    type: 'Cessna 172S Skyhawk SP',
    year: null,
    category: 'taa',
    seats: 4,
    engine: 'Lycoming IO-360-L2A · 180 hp (fuel injected)',
    fuelCapacity: '53 gal usable (56 gal total)',
    emptyWeight: 1663,
    maxGross: 2550,
    usefulLoad: 887,
    fuelWeight: 318,        // 53 gal × 6 lbs
    payloadWithFuel: 569,
    cg: { fwd: 35.0, aft: 47.3, datum: 'firewall' },
    stations: [
      { name: 'Front Seats', arm: 37.0, maxWeight: 400 },
      { name: 'Rear Seats', arm: 73.0, maxWeight: 340 },
      { name: 'Fuel (53 gal)', arm: 48.0, maxWeight: 318 },
      { name: 'Baggage A', arm: 95.0, maxWeight: 120 },
      { name: 'Baggage B', arm: 123.0, maxWeight: 50 },
    ],
    avionics: 'TAA: Garmin G3X, GNX375, GFC500 Autopilot, ADS-B In/Out',
    rates: { member: 165, prepay: 160.05, nonMember: 185 },
    rateUnit: 'Hobbs hr (wet)',
    soloInsurance: 'Private',
    status: 'airworthy',
    role: 'TAA · IFR · Cross-country · Autopilot',
    notes: 'Technically Advanced Aircraft. Full Garmin glass cockpit. GFC500 autopilot. Fuel injected. Requires Private certificate to rent solo.',
  },
  {
    id: 'n401ss',
    tailNumber: 'N401SS',
    type: 'Cessna 182P Skylane',
    year: null,
    category: 'high-performance',
    seats: 4,
    engine: 'Continental O-470-R · 230 hp',
    fuelCapacity: '65 gal usable (79 gal total)',
    emptyWeight: 1645,
    maxGross: 2950,
    usefulLoad: 1305,
    fuelWeight: 390,        // 65 gal × 6 lbs
    payloadWithFuel: 915,
    cg: { fwd: 35.0, aft: 47.3, datum: 'firewall' },
    stations: [
      { name: 'Front Seats', arm: 37.0, maxWeight: 400 },
      { name: 'Rear Seats', arm: 73.0, maxWeight: 400 },
      { name: 'Fuel (65 gal)', arm: 46.0, maxWeight: 390 },
      { name: 'Baggage', arm: 95.0, maxWeight: 200 },
    ],
    avionics: 'Garmin 650, Garmin Aera 560, Lynx 9000 ADS-B In/Out',
    rates: { member: 174, prepay: 168.78, nonMember: 194 },
    rateUnit: 'Hobbs hr (wet)',
    soloInsurance: 'Pvt & 100TT, 15 takeoff & landing in make & model',
    status: 'airworthy',
    role: 'High-performance · Mountain flying · Load hauler',
    notes: 'High-performance endorsement required. 230 hp. Best mountain airplane in the fleet. Requires Private + 100 hrs TT + 15 landings in type.',
  },
  {
    id: 'n501el',
    tailNumber: 'N501EL',
    type: 'American Champion Citabria 7ECA',
    year: null,
    category: 'tailwheel',
    seats: 2,
    engine: 'Lycoming O-235 · 115 hp',
    fuelCapacity: '26 gal usable',
    emptyWeight: 1150,
    maxGross: 1650,
    usefulLoad: 500,
    fuelWeight: 156,        // 26 gal × 6 lbs
    payloadWithFuel: 344,
    cg: { fwd: 11.0, aft: 19.0, datum: 'wing leading edge' },
    stations: [
      { name: 'Front Seat', arm: 14.0, maxWeight: 190 },
      { name: 'Rear Seat', arm: 25.0, maxWeight: 190 },
      { name: 'Fuel (26 gal)', arm: 18.0, maxWeight: 156 },
      { name: 'Baggage', arm: 42.0, maxWeight: 50 },
    ],
    avionics: 'Garmin 496 GPS, GTX 327 Transponder',
    rates: { member: 182, prepay: 176.54, nonMember: 202 },
    rateUnit: 'Hobbs hr (wet)',
    soloInsurance: 'Dual instruction only',
    status: 'airworthy',
    role: 'Tailwheel endorsement · Aerobatics · Spin training',
    notes: 'Dual instruction only — no solo rental. Tandem seating. Conventional gear. Aerobatic. Tailwheel instruction may incur parachute rental fee.',
  },
  {
    id: 'n12ja',
    tailNumber: 'N12JA',
    type: 'Pipistrel Alpha Trainer',
    year: 2023,
    category: 'lsa',
    seats: 2,
    engine: 'Rotax 912 UL · 80 hp',
    fuelCapacity: '24 gal usable',
    emptyWeight: 615,
    maxGross: 1212,
    usefulLoad: 597,
    fuelWeight: 144,        // 24 gal × 6 lbs
    payloadWithFuel: 453,
    cg: { fwd: null, aft: null, datum: 'reference datum' },
    stations: [
      { name: 'Occupants (side-by-side)', arm: null, maxWeight: 453 },
      { name: 'Fuel (24 gal)', arm: null, maxWeight: 144 },
    ],
    avionics: 'GTR200, GTX445, Garmin 600 GPS, BPRS Ballistic Parachute',
    rates: { member: 119, prepay: 115.43, nonMember: 139 },
    rateUnit: 'Tach hr (wet)',
    soloInsurance: 'Student',
    status: 'airworthy',
    role: 'Sport pilot training · Primary trainer · Most affordable',
    notes: '2023 — newest trainer on the Front Range. BPRS ballistic parachute. Extremely fuel efficient. Reduced noise. Tach time billing.',
  },
  {
    id: 'n202mm',
    tailNumber: 'N202MM',
    type: 'Pipistrel Virus SW iS 100',
    year: null,
    category: 'lsa',
    seats: 2,
    engine: 'Rotax 912 iS · 100 hp (fuel injected)',
    fuelCapacity: '28 gal usable',
    emptyWeight: 633,
    maxGross: 1041,
    usefulLoad: 408,
    fuelWeight: 168,        // 28 gal × 6 lbs
    payloadWithFuel: 240,
    cg: { fwd: null, aft: null, datum: 'reference datum' },
    stations: [
      { name: 'Occupants (side-by-side)', arm: null, maxWeight: 240 },
      { name: 'Fuel (28 gal)', arm: null, maxWeight: 168 },
    ],
    avionics: 'TAA: GMA245R, Garmin 650 NavCom, Autopilot, BPRS Ballistic Parachute',
    rates: { member: 139, prepay: 134.83, nonMember: 159 },
    rateUnit: 'Tach hr (wet)',
    soloInsurance: 'Student',
    status: 'airworthy',
    role: 'Sport pilot training · Cross-country LSA',
    notes: 'TAA Light Sport. Fuel injected. Autopilot. BPRS parachute. High cruise speed for an LSA. Tach time billing.',
  },
  {
    id: 'sim',
    tailNumber: 'SIM',
    type: 'Precision Flight Controls CRX MAX',
    year: null,
    category: 'sim',
    seats: 1,
    engine: 'N/A',
    fuelCapacity: 'N/A',
    emptyWeight: null,
    maxGross: null,
    usefulLoad: null,
    fuelWeight: null,
    payloadWithFuel: null,
    cg: null,
    stations: null,
    avionics: 'Various — configurable for multiple aircraft types',
    rates: { member: 65, prepay: 65, nonMember: 85 },
    rateUnit: 'hr',
    soloInsurance: 'Solo members only rental during business hours',
    status: 'airworthy',
    role: 'FAA AATD · Instrument training · Procedures',
    notes: 'FAA-approved Advanced Aviation Training Device. Log instrument time. Solo members only during business hours.',
  },
]

/* ──────────────── MEMBERSHIP ──────────────── */
export const JB_MEMBERSHIP = {
  standard: { monthly: 35, annual: 360 },
  discounted: { monthly: 15, note: 'High school/college students, healthcare workers, veterans' },
}

/* ──────────────── INSTRUCTION RATES ──────────────── */
export const JB_INSTRUCTION_RATES = {
  primary:    { rate: 59, label: 'Primary (Intro / Private Pilot)', perHour: true },
  advanced:   { rate: 64, label: 'Advanced (Ratings past Private, BFRs)', perHour: true },
  specialty:  { rate: 74, label: 'Multi-Engine / Mountain / Tailwheel', perHour: true },
  note: 'Flight instruction may be billed for total time with CFI, not just flight time. Tailwheel instruction may incur parachute rental fee.',
}

/* ──────────────── INSURANCE REQUIREMENTS ──────────────── */
export const JB_INSURANCE = {
  liability: 250000,
  medical: 1000,
  physicalDamage: 25000,
  providers: [
    { name: 'Avemco (preferred)', url: 'https://www.avemco.com/ja09' },
    { name: 'Southwest Aviation Insurance', url: 'https://www.southwestaviationinsurance.com' },
    { name: 'EAA', url: 'https://www.eaa.aeroinsure.com' },
    { name: 'AOPA / AP Aerospace', url: 'https://www.ap-aerospace.com' },
  ],
  note: 'Non-owned Renter\'s Insurance required to act as PIC.',
}

/* ──────────────── FUEL ──────────────── */
export const JB_FUEL = {
  brand: 'AVFUEL',
  types: [
    { type: '100LL', selfServe: 5.79, fullServe: 6.49, unit: 'gal' },
    { type: 'Jet-A', selfServe: null, fullServe: 6.50, unit: 'gal' },
    { type: 'Jet-A + Prist', selfServe: null, fullServe: 6.50, unit: 'gal' },
  ],
  note: 'Self-serve 100LL available. Full-serve Jet-A truck. Minimum charge may apply.',
}

/* ──────────────── FBO SERVICES ──────────────── */
export const JB_FBO_SERVICES = [
  'Jet-A & 100LL fueling (self-serve and full-serve)',
  'Heated hangar rental (daily & monthly)',
  'Tie-down rental (daily & monthly)',
  'Flight planning room',
  'Pilot supplies',
  'Coffee & snack bar',
  'EV charging (Automotive Class II)',
  'Clean restrooms & rest areas',
  'Aircraft cleaning',
  'Snow removal & aircraft preheating',
  'Tug service',
  'Aircraft maintenance — A&P, IA, Rotax iRMT Series 9',
  'ROTAX Independent Repair Centre (iRC)',
  'SLSA maintenance and repair',
  'Annual, 100-hour, conditional & pre-buy inspections',
  'Aircraft leaseback program',
]

/* ──────────────── TRAINING PROGRAMS ──────────────── */
export const JB_TRAINING = [
  { id: 'discovery', name: 'Discovery Flight', desc: 'Introductory flight lesson — you fly a Cessna or Pipistrel over Boulder with an instructor.' },
  { id: 'private', name: 'Private Pilot Certificate', desc: 'Part 61 training from zero to Private Pilot checkride. Fly single-engine land.' },
  { id: 'instrument', name: 'Instrument Rating', desc: 'Fly in clouds and low visibility. IFR training with AATD simulator and Garmin-equipped aircraft.' },
  { id: 'commercial', name: 'Commercial Pilot Certificate', desc: 'Advanced training to fly for compensation or hire.' },
  { id: 'cfi', name: 'CFI / CFII', desc: 'Flight Instructor and Instrument Instructor certificates.' },
  { id: 'hp', name: 'High-Performance Endorsement', desc: 'Cessna 182 checkout. Required for engines over 200 hp.' },
  { id: 'tailwheel', name: 'Tailwheel Endorsement', desc: 'Conventional gear training in the Citabria 7ECA.' },
  { id: 'mountain', name: 'Mountain Flying', desc: 'Density altitude, canyon winds, terrain awareness in the Rocky Mountains.' },
  { id: 'spin', name: 'Spin Awareness', desc: 'Entry, recognition, and recovery training in the Citabria.' },
  { id: 'ipc', name: 'Instrument Proficiency Check', desc: 'Get current on instruments. Required every 6 months without IFR activity.' },
  { id: 'bfr', name: 'Flight Review (BFR)', desc: '1 hr ground + 1 hr flight. Required every 24 calendar months.' },
  { id: 'taa', name: 'TAA Training', desc: 'Technically Advanced Aircraft checkout — Garmin G3X, GFC500 autopilot.' },
  { id: 'sim', name: 'AATD Simulator', desc: 'Instrument procedures in the CRX MAX sim. Loggable time.' },
  { id: 'glider', name: 'Glider Training', desc: 'Glider pilot training available through the flight school.' },
  { id: 'ground', name: 'Ground School', desc: 'Private, instrument, and commercial ground instruction.' },
  { id: 'accelerated', name: 'Accelerated Programs', desc: 'Intensive Private, Instrument, and Commercial — finish in weeks, not months.' },
]

/* ──────────────── GALLERY ──────────────── */
// Aircraft type photos moved to ../portal/portalConstants.js (shared across all portals)

// Gallery images — real photos from journeysaviation.com
const JB_IMG_BASE = 'https://www.journeysaviation.com/uploads/1/3/2/8/132898297'
export const JB_GALLERY = [
  // Fleet
  { id: 1, alt: 'Cessna 172S N3547L — TAA glass cockpit trainer', category: 'fleet', img: `${JB_IMG_BASE}/n3547l-orig_orig.jpg` },
  { id: 2, alt: 'Pipistrel Alpha Trainer N12JA on the ramp', category: 'fleet', img: `${JB_IMG_BASE}/n12ja_orig.jpg` },
  { id: 3, alt: 'Pipistrel Alpha Trainer — newest on the Front Range', category: 'fleet', img: `${JB_IMG_BASE}/published/n12ja.jpg?1733952054` },
  { id: 4, alt: 'Cessna training fleet lined up on the ramp', category: 'fleet', img: `${JB_IMG_BASE}/img-9118_3.jpg` },
  // Training
  { id: 5, alt: 'Cockpit view during dual flight instruction', category: 'training', img: `${JB_IMG_BASE}/published/img-9118.jpg?1733952061` },
  { id: 6, alt: 'Flight training at Journeys Aviation', category: 'training', img: `${JB_IMG_BASE}/editor/flight-training.jpeg?1769028309` },
  { id: 7, alt: 'Accelerated program — student pre-flight', category: 'training', img: `${JB_IMG_BASE}/published/img-5850_1.jpeg` },
  { id: 8, alt: 'Cessna 172 ready for a training flight', category: 'training', img: `${JB_IMG_BASE}/img-5856_1.jpeg` },
  // FBO
  { id: 9, alt: 'Journeys Aviation FBO at Boulder Municipal', category: 'fbo', img: `${JB_IMG_BASE}/new-photo-10-2024_orig.jpg` },
  { id: 10, alt: 'Journeys Aviation ramp — Boulder Airport', category: 'fbo', img: `${JB_IMG_BASE}/img-2393_orig.jpeg` },
  { id: 11, alt: 'AVFUEL — aviation fuel services', category: 'fbo', img: `${JB_IMG_BASE}/editor/avfuelbrandlogo.jpeg?1769054186` },
  { id: 12, alt: 'ROTAX Independent Repair Centre', category: 'fbo', img: `${JB_IMG_BASE}/published/rotax-irc-logo.png?1769056482` },
  // Operations
  { id: 13, alt: 'Boulder Municipal Airport operations', category: 'flights', img: `${JB_IMG_BASE}/editor/img-2983.jpg?1768244155` },
  { id: 14, alt: 'Airport overview — runway 08/26 at KBDU', category: 'flights', img: `${JB_IMG_BASE}/editor/screenshot-2025-02-24-at-6-15-52-pm.png?1740446190` },
  { id: 15, alt: 'Glider operations at Boulder Airport', category: 'flights', img: `${JB_IMG_BASE}/71w_orig.png` },
  // Team
  { id: 16, alt: 'Andrew McKenna — President & CEO', category: 'team', img: `${JB_IMG_BASE}/published/amck-oic-2.jpg?1605481695` },
  { id: 17, alt: 'Scott Griffith — Assistant Manager', category: 'team', img: `${JB_IMG_BASE}/published/scottgriffith_1.jpg` },
  { id: 18, alt: 'Tess Kim — Accounting', category: 'team', img: `${JB_IMG_BASE}/published/tessk.jpg?1734230262` },
  { id: 19, alt: 'Sean A. — Line Technician', category: 'team', img: `${JB_IMG_BASE}/published/seana.png?1734230719` },
  { id: 20, alt: 'Alex S. — Customer Service', category: 'team', img: `${JB_IMG_BASE}/editor/alex-web-pic.jpeg?1766856605` },
]

/* ──────────────── RESOURCES ──────────────── */
export const JB_RESOURCES = [
  { label: 'Aircraft Rental Rates & Insurance (PDF)', url: 'http://journeysaviation.com/uploads/1/3/2/8/132898297/aircraft_rental_price_list_12.1.2023.pdf' },
  { label: 'Aircraft Checkout Form (PDF)', url: 'https://www.journeysaviation.com/aircraft-fleet.html' },
  { label: 'Aircraft Weight & Balance Calculator', url: 'https://www.journeysaviation.com/aircraft-fleet.html' },
  { label: 'Avemco Renters Insurance (preferred)', url: 'https://www.avemco.com/ja09' },
  { label: 'FAA Pilot Handbook (FAA-H-8083-25B)', url: 'https://www.faa.gov/regulations_policies/handbooks_manuals/aviation/phak' },
  { label: 'FAA Instrument Flying Handbook', url: 'https://www.faa.gov/regulations_policies/handbooks_manuals/aviation/media/FAA-H-8083-15B.pdf' },
  { label: 'Boulder METAR / TAF', url: 'https://aviationweather.gov/data/metar/?id=KBDU&hours=6' },
  { label: 'AOPA Airport Info (KBDU)', url: 'https://www.aopa.org/destinations/business/29676' },
  { label: 'AirNav (KBDU / Journeys)', url: 'http://www.airnav.com/airport/KBDU/JOURNEYS_AV' },
  { label: 'EAA Chapter 1627 (Boulder)', url: 'https://www.eaa.org/eaa/eaa-chapters/find-an-eaa-chapter' },
]

/* ──────────────── SIMULATED "TODAY'S OPS" ──────────────── */
export function getJBTodayOps() {
  const hour = new Date().getHours()
  const isOpen = hour >= 8 && hour < 17
  return {
    isOpen,
    fieldElevation: '5,288 ft MSL',
    runwayInUse: '08/26',
    windDir: isOpen ? `${210 + Math.floor(Math.random() * 50)}°` : '--',
    windSpeed: isOpen ? `${4 + Math.floor(Math.random() * 12)} kt` : '--',
    temp: isOpen ? `${52 + Math.floor(Math.random() * 22)}°F` : '--',
    visibility: isOpen ? `${8 + Math.floor(Math.random() * 5)} SM` : '--',
    densityAltitude: isOpen ? `${6200 + Math.floor(Math.random() * 1800)} ft` : '--',
    cloudBase: isOpen ? `${9500 + Math.floor(Math.random() * 4000)} ft MSL` : '--',
    aircraftAvailable: isOpen ? Math.floor(Math.random() * 4) + 6 : '--',
    nextSunset: '19:38 MDT',
  }
}
