// =============================================================================
// FlightSafe Maintenance — Mock Database
// Mirrors the SQLite schema in schema.sql
// Reference date: 2026-03-28
// Aircraft fleet: N12345 (BE58), N67890 (C172S), N11111 (PA28),
//                 N22222 (C208), N33333 (C172N-GROUNDED), N44444 (PA34),
//                 N55555 (C208B)
// =============================================================================

// ─── Squawks ──────────────────────────────────────────────────────────────────
// severity: grounding | ops_limiting | deferred | monitoring
// status:   open | in_progress | deferred_mel | closed

export const mockSquawks = [
  // N33333 — GROUNDED (oil pressure + brake)
  {
    id: 'sqk-001',
    tailNumber: 'N33333',
    reportedBy: 'Capt. Dana Wells',
    reportedDate: '2026-03-20',
    description: 'Oil pressure fluctuating 20–60 PSI during engine run-up. Drops below green arc at idle.',
    severity: 'grounding',
    status: 'in_progress',
    melReference: null,
    melExpiryDate: null,
    airframeHours: 6810,
    resolvedDate: null,
    resolvedBy: null,
    resolutionNotes: null,
    workOrderId: 'wo-001',
  },
  {
    id: 'sqk-002',
    tailNumber: 'N33333',
    reportedBy: 'Capt. Dana Wells',
    reportedDate: '2026-03-20',
    description: 'Right brake dragging on rollout — requires excessive left rudder to maintain centerline.',
    severity: 'ops_limiting',
    status: 'in_progress',
    melReference: null,
    melExpiryDate: null,
    airframeHours: 6810,
    resolvedDate: null,
    resolvedBy: null,
    resolutionNotes: null,
    workOrderId: 'wo-002',
  },

  // N11111 — open altimeter squawk
  {
    id: 'sqk-003',
    tailNumber: 'N11111',
    reportedBy: 'FO Marcus Chen',
    reportedDate: '2026-03-25',
    description: 'Altimeter #2 reads +80 ft off at field elevation. Discrepancy increases at altitude.',
    severity: 'ops_limiting',
    status: 'open',
    melReference: null,
    melExpiryDate: null,
    airframeHours: 3415,
    resolvedDate: null,
    resolvedBy: null,
    resolutionNotes: null,
    workOrderId: null,
  },

  // N67890 — MEL'd pitot heat
  {
    id: 'sqk-004',
    tailNumber: 'N67890',
    reportedBy: 'FO Jamie Rivera',
    reportedDate: '2026-03-16',
    description: 'Pitot heat element burned out. No heat output on test.',
    severity: 'ops_limiting',
    status: 'deferred_mel',
    melReference: 'MEL 34-11-1 (Cat C)',
    melExpiryDate: '2026-04-15',
    airframeHours: 1120,
    resolvedDate: null,
    resolvedBy: null,
    resolutionNotes: null,
    workOrderId: 'wo-003',
  },

  // N22222 — autopilot altitude hold MEL'd
  {
    id: 'sqk-005',
    tailNumber: 'N22222',
    reportedBy: 'Capt. Ray Kimura',
    reportedDate: '2026-03-18',
    description: 'Autopilot altitude hold mode not engaging. CWS and heading hold functional.',
    severity: 'deferred',
    status: 'deferred_mel',
    melReference: 'MEL 22-10-2 (Cat B)',
    melExpiryDate: '2026-04-17',
    airframeHours: 5220,
    resolvedDate: null,
    resolvedBy: null,
    resolutionNotes: null,
    workOrderId: 'wo-004',
  },

  // N12345 — monitoring item, recent
  {
    id: 'sqk-006',
    tailNumber: 'N12345',
    reportedBy: 'Capt. A. Torres',
    reportedDate: '2026-03-26',
    description: 'Slight vibration felt in left seat at Vno cruise. Possibly prop balance — no loss of performance.',
    severity: 'monitoring',
    status: 'open',
    melReference: null,
    melExpiryDate: null,
    airframeHours: 2840,
    resolvedDate: null,
    resolvedBy: null,
    resolutionNotes: null,
    workOrderId: null,
  },

  // Historical — closed squawks
  {
    id: 'sqk-007',
    tailNumber: 'N44444',
    reportedBy: 'FO S. Patel',
    reportedDate: '2026-01-12',
    description: 'Right main gear door slow to close — 4-second delay after gear up.',
    severity: 'deferred',
    status: 'closed',
    melReference: null,
    melExpiryDate: null,
    airframeHours: 2090,
    resolvedDate: '2026-01-18',
    resolvedBy: 'A&P Mike Ferris',
    resolutionNotes: 'Adjusted actuator linkage, lubricated gear door hinges. Functional check OK.',
    workOrderId: 'wo-005',
  },
  {
    id: 'sqk-008',
    tailNumber: 'N55555',
    reportedBy: 'Capt. L. Nguyen',
    reportedDate: '2026-02-20',
    description: 'Cabin heat control stiff — requires excessive force to move from full hot.',
    severity: 'monitoring',
    status: 'closed',
    melReference: null,
    melExpiryDate: null,
    airframeHours: 1880,
    resolvedDate: '2026-02-25',
    resolvedBy: 'A&P/IA Sarah Cole',
    resolutionNotes: 'Replaced heater control cable assembly. Smooth operation confirmed.',
    workOrderId: 'wo-006',
  },
  {
    id: 'sqk-009',
    tailNumber: 'N12345',
    reportedBy: 'Capt. A. Torres',
    reportedDate: '2026-01-05',
    description: 'Left landing light intermittent at high vibration.',
    severity: 'deferred',
    status: 'closed',
    melReference: null,
    melExpiryDate: null,
    airframeHours: 2810,
    resolvedDate: '2026-01-10',
    resolvedBy: 'A&P T. Brooks',
    resolutionNotes: 'Replaced landing light socket and bulb. Both lights operational.',
    workOrderId: null,
  },
]

// ─── Work Orders ──────────────────────────────────────────────────────────────
// priority:             aog | urgent | routine | scheduled
// status:               open | in_progress | parts_on_order | completed | deferred | cancelled
// type:                 inspection | repair | ad_compliance | overhaul | preventive | squawk
// location:             hangar | ramp | maintenance_bay | remote | shop
// holdReason:           queued | awaiting_hangar | awaiting_tech | parts_hold |
//                       priority_hold | awaiting_approval | weather | deferred_ops
// assignedPersonnelIds:    array of personnel IDs (from mocks/personnel.js)
// supervisorId:            personnel ID of the A&P supervising this task (14 CFR 43.3)
// supervisorCertificateId: specific certificate ID (from mockCertificates) under which
//                          supervision is performed — required by 14 CFR 43.9(a)(3).
//                          The certificate status must be 'active' for this to be valid.
// accruingHours:           true if labor hours are actively accumulating right now

export const mockWorkOrders = [
  // AOG — N33333 engine investigation (in maintenance bay, blocked on parts)
  {
    id: 'wo-001',
    tailNumber: 'N33333',
    createdDate: '2026-03-20',
    priority: 'aog',
    type: 'repair',
    title: 'Oil pressure fluctuation — engine teardown and inspect',
    description:
      'Investigate and repair oil pressure fluctuation reported during run-up. Possible causes: oil pressure relief valve, oil pump wear, clogged oil pick-up screen. Per 14 CFR 43.13, perform in accordance with manufacturer\'s service manual.',
    assignedPersonnelIds: ['prs-011'],   // Sarah Cole — lead tech
    supervisorId: 'prs-011',             // Sarah Cole signs RTS (IA)
    supervisorCertificateId: 'cert-005', // IA-991055 — required for engine work RTS
    accruingHours: true,                 // actively working engine teardown
    startedAt: '2026-03-20T09:15:00',   // teardown started day of squawk discovery
    status: 'parts_on_order',
    location: 'maintenance_bay',
    holdReason: 'parts_hold',
    queuePosition: null,
    estimatedHours: 12,
    actualHours: 4,
    partsCost: 0,
    laborCost: 0,
    completedDate: null,
    deferredTo: null,
    notes: 'Engine partially disassembled. Oil pump confirmed worn — replacement on order. Oil relief valve also ordered pending inspection.',
  },

  // URGENT — N33333 brake repair (in same bay, parts arriving)
  {
    id: 'wo-002',
    tailNumber: 'N33333',
    createdDate: '2026-03-20',
    priority: 'urgent',
    type: 'repair',
    title: 'Right brake drag — master cylinder and caliper inspection',
    description:
      'Inspect and repair right brake dragging. Check brake master cylinder, caliper piston, and brake lines for restriction or sticking. Replace brake pads if worn below limits per Cessna AMM Chapter 32.',
    assignedPersonnelIds: ['prs-012'],   // Mike Ferris — lead tech
    supervisorId: 'prs-011',             // Sarah Cole signs RTS
    supervisorCertificateId: 'cert-004', // AME-991055 A&P (cert-005 IA not needed for brake repair)
    accruingHours: false,                // waiting on master cylinder (ETA 2026-04-01)
    startedAt: '2026-03-20T14:30:00',   // initial assessment completed, now on hold
    status: 'parts_on_order',
    location: 'maintenance_bay',
    holdReason: 'parts_hold',
    queuePosition: null,
    estimatedHours: 4,
    actualHours: 2,
    partsCost: 0,
    laborCost: 0,
    completedDate: null,
    deferredTo: null,
    notes: 'Right master cylinder confirmed failed — internal bypass. Caliper inspected serviceable. Brake pads at minimum limits — replacing.',
  },

  // Parts on order — N67890 pitot heat (aircraft on ramp, MEL active)
  {
    id: 'wo-003',
    tailNumber: 'N67890',
    createdDate: '2026-03-17',
    priority: 'routine',
    type: 'repair',
    title: 'Pitot heat element replacement (MEL 34-11-1)',
    description:
      'Replace failed pitot heat element. P/N 0411260 (Garmin/Cessna). Aircraft operating under MEL Cat C — 30-day limit. Must complete prior to 2026-04-15. Return pitot heat to operational status per C172S AMM Chapter 30.',
    assignedPersonnelIds: ['prs-008'],   // Tyler Brooks — will install when part arrives
    supervisorId: 'prs-011',             // Sarah Cole signs RTS
    supervisorCertificateId: 'cert-004', // AME-991055 A&P
    accruingHours: false,                // waiting on pitot heat element ETA 2026-03-31
    startedAt: '2026-03-17T11:00:00',   // squawk written, initial assessment done
    status: 'parts_on_order',
    location: 'ramp',
    holdReason: 'parts_hold',
    queuePosition: null,
    estimatedHours: 2,
    actualHours: null,
    partsCost: 285,
    laborCost: 0,
    completedDate: null,
    deferredTo: null,
    notes: 'Aircraft flyable under MEL. Part arriving 2026-03-31, work scheduled same day. MEL expires 2026-04-15 — on track.',
  },

  // Routine — N22222 autopilot (in hangar, blocked on tech availability)
  {
    id: 'wo-004',
    tailNumber: 'N22222',
    createdDate: '2026-03-19',
    priority: 'routine',
    type: 'repair',
    title: 'Autopilot altitude hold fault — Garmin GFC 700 troubleshoot',
    description:
      'Diagnose and repair autopilot altitude hold fault (MEL 22-10-2, Cat B, 30 days). Connect Garmin GSA 80/81 servo tester. Check altitude hold engage logic, barometric sensor input to GFC 700. May require servo replacement.',
    assignedPersonnelIds: ['prs-013'],   // T. Huang — Garmin avionics specialist
    supervisorId: 'prs-011',             // Sarah Cole oversees / signs RTS
    supervisorCertificateId: 'cert-004', // AME-991055 A&P (avionics sign-off)
    accruingHours: false,                // T. Huang not on-site until 2026-04-02
    scheduledDate: '2026-04-02',         // tech available date (ADS-B source: T. Huang)
    status: 'open',
    location: 'hangar',
    holdReason: 'awaiting_tech',
    queuePosition: null,
    estimatedHours: 6,
    actualHours: null,
    partsCost: 0,
    laborCost: 0,
    completedDate: null,
    deferredTo: null,
    notes: 'Avionics tech T. Huang scheduled 2026-04-02. Aircraft in hangar. MEL expires 2026-04-17 — 15 days remaining.',
  },

  // Scheduled — N11111 annual + 100hr (on ramp, queued #1, due in 5 days)
  {
    id: 'wo-005',
    tailNumber: 'N11111',
    createdDate: '2026-03-28',
    priority: 'scheduled',
    type: 'inspection',
    title: 'Annual + 100hr combined inspection (due 2026-04-02 / 2026-04-15)',
    description:
      'Perform combined annual and 100-hour inspection per 14 CFR 91.409(a)(b). Inspect per Piper PA-28 Maintenance Manual. Address open AD 2024-11-03 (fuel selector valve) and altimeter squawk sqk-003 simultaneously. Requires IA sign-off for annual.',
    assignedPersonnelIds: ['prs-011'],   // Sarah Cole — IA required for annual sign-off
    supervisorId: 'prs-011',
    supervisorCertificateId: 'cert-005', // IA-991055 — IA required for annual (14 CFR 65.95)
    accruingHours: false,                // queued — work not started
    status: 'open',
    location: 'ramp',
    holdReason: 'queued',
    queuePosition: 1,
    estimatedHours: 24,
    actualHours: null,
    partsCost: 0,
    laborCost: 0,
    completedDate: null,
    deferredTo: null,
    notes: '100hr due 2026-04-02 — 5 DAYS. Queued for maintenance bay #2 when N33333 clears. Sarah Cole assigned.',
  },

  // Urgent — N11111 AD (bundled with wo-005, same queue slot)
  {
    id: 'wo-006',
    tailNumber: 'N11111',
    createdDate: '2026-03-28',
    priority: 'urgent',
    type: 'ad_compliance',
    title: 'AD 2024-11-03 Compliance — fuel selector valve inspection',
    description:
      'Comply with AD 2024-11-03: inspect fuel selector valve for improper detent engagement per Piper SB-1298. Aircraft may not fly after next inspection due. Bundle with wo-005 combined annual/100hr.',
    assignedPersonnelIds: ['prs-011'],   // Sarah Cole — bundled with wo-005
    supervisorId: 'prs-011',
    supervisorCertificateId: 'cert-004', // AME-991055 A&P
    accruingHours: false,                // queued
    status: 'open',
    location: 'ramp',
    holdReason: 'queued',
    queuePosition: 1,
    estimatedHours: 3,
    actualHours: null,
    partsCost: 0,
    laborCost: 0,
    completedDate: null,
    deferredTo: null,
    notes: 'Bundled with wo-005. Valve replacement kit pre-ordered pending inspection findings.',
  },

  // Scheduled — N44444 100hr (on ramp, queued #2, due 28 days)
  {
    id: 'wo-007',
    tailNumber: 'N44444',
    createdDate: '2026-03-28',
    priority: 'scheduled',
    type: 'inspection',
    title: '100-hour inspection — due 2026-04-25',
    description:
      'Perform 100-hour inspection per 14 CFR 91.409(b) and Piper PA-34 Maintenance Manual. Inspect both Continental TSIO-360-RB engines, propellers, airframe, and systems.',
    assignedPersonnelIds: [],            // not yet assigned — needs mechanic by 2026-04-18
    supervisorId: 'prs-011',             // Sarah Cole will supervise
    supervisorCertificateId: 'cert-004', // AME-991055 A&P (cert-005 IA if inspection sign-off needed)
    accruingHours: false,                // queued — unassigned
    status: 'open',
    location: 'ramp',
    holdReason: 'queued',
    queuePosition: 2,
    estimatedHours: 20,
    actualHours: null,
    partsCost: 0,
    laborCost: 0,
    completedDate: null,
    deferredTo: null,
    notes: 'Queued for maintenance bay after N11111 clears. Assign mechanic by 2026-04-18.',
  },

  // Completed — historical records
  {
    id: 'wo-008',
    tailNumber: 'N44444',
    createdDate: '2026-01-12',
    priority: 'routine',
    type: 'squawk',
    title: 'Right main gear door slow to close',
    description: 'Adjust actuator linkage and lubricate gear door hinges per PA-34 AMM.',
    assignedPersonnelIds: ['prs-012'],   // Mike Ferris
    supervisorId: 'prs-011',
    supervisorCertificateId: 'cert-004', // AME-991055 A&P
    accruingHours: false,                // completed
    status: 'completed',
    location: 'hangar',
    holdReason: null,
    queuePosition: null,
    estimatedHours: 3,
    actualHours: 2.5,
    partsCost: 45,
    laborCost: 187.50,
    completedDate: '2026-01-18',
    deferredTo: null,
    notes: null,
  },
  {
    id: 'wo-009',
    tailNumber: 'N55555',
    createdDate: '2026-02-20',
    priority: 'routine',
    type: 'squawk',
    title: 'Cabin heat control cable replacement',
    description: 'Replace heater control cable assembly. Confirm smooth operation.',
    assignedPersonnelIds: ['prs-011'],   // Sarah Cole
    supervisorId: 'prs-011',
    supervisorCertificateId: 'cert-004', // AME-991055 A&P
    accruingHours: false,                // completed
    status: 'completed',
    location: 'hangar',
    holdReason: null,
    queuePosition: null,
    estimatedHours: 2,
    actualHours: 1.5,
    partsCost: 120,
    laborCost: 112.50,
    completedDate: '2026-02-25',
    deferredTo: null,
    notes: null,
  },
  {
    id: 'wo-010',
    tailNumber: 'N55555',
    createdDate: '2026-02-15',
    priority: 'scheduled',
    type: 'inspection',
    title: 'Annual + 100hr combined inspection',
    description: 'Combined annual/100hr per 14 CFR 91.409(a)(b). C208B maintenance manual. PT6A-114A engine borescope.',
    assignedPersonnelIds: ['prs-011'],   // Sarah Cole — IA sign-off
    supervisorId: 'prs-011',
    supervisorCertificateId: 'cert-005', // IA-991055 — annual inspection requires IA
    accruingHours: false,                // completed
    status: 'completed',
    location: 'hangar',
    holdReason: null,
    queuePosition: null,
    estimatedHours: 30,
    actualHours: 28,
    partsCost: 1840,
    laborCost: 2100,
    completedDate: '2026-02-19',
    deferredTo: null,
    notes: 'Engine borescope — all combustion sections within limits. No hot-section wear noted.',
  },
]

// ─── Parts ────────────────────────────────────────────────────────────────────
// status: not_ordered | ordered | in_transit | arrived | backordered | installed | cancelled
//
// Pipeline: not_ordered → ordered → in_transit → arrived → installed
//           (backordered and cancelled are branch statuses)

export const mockParts = [
  // ── wo-001 (N33333 engine teardown) ──
  {
    id: 'prt-001',
    workOrderId: 'wo-001',
    tailNumber: 'N33333',
    partNumber: '649831-1',
    description: 'Oil pump assembly — Lycoming O-320-H2AD',
    quantity: 1,
    unitCost: 680,
    supplier: 'Lycoming Factory',
    poNumber: 'PO-2026-0312',
    orderedDate: '2026-03-22',
    etaDate: '2026-03-29',
    arrivedDate: null,
    installedDate: null,
    status: 'in_transit',
    notes: 'AOG shipping. Tracking # LYC-88219. Arrives 2026-03-29.',
  },
  {
    id: 'prt-002',
    workOrderId: 'wo-001',
    tailNumber: 'N33333',
    partNumber: '75976',
    description: 'Oil pressure relief valve',
    quantity: 1,
    unitCost: 128,
    supplier: 'Aircraft Spruce',
    poNumber: 'PO-2026-0313',
    orderedDate: '2026-03-22',
    etaDate: '2026-04-01',
    arrivedDate: null,
    installedDate: null,
    status: 'ordered',
    notes: 'Standard ground shipping. Will inspect original before installing.',
  },
  {
    id: 'prt-003',
    workOrderId: 'wo-001',
    tailNumber: 'N33333',
    partNumber: '67818',
    description: 'Oil suction screen assembly',
    quantity: 1,
    unitCost: 42,
    supplier: 'Aircraft Spruce',
    poNumber: 'PO-2026-0313',
    orderedDate: '2026-03-22',
    etaDate: '2026-04-01',
    arrivedDate: '2026-03-26',
    installedDate: null,
    status: 'arrived',
    notes: 'In stock — arrived same day. Awaiting engine reassembly.',
  },
  {
    id: 'prt-004',
    workOrderId: 'wo-001',
    tailNumber: 'N33333',
    partNumber: 'LW-12404',
    description: 'Gasket set — engine lower',
    quantity: 1,
    unitCost: 95,
    supplier: 'Aircraft Spruce',
    poNumber: 'PO-2026-0313',
    orderedDate: '2026-03-22',
    etaDate: '2026-04-01',
    arrivedDate: '2026-03-26',
    installedDate: null,
    status: 'arrived',
    notes: null,
  },

  // ── wo-002 (N33333 brake) ──
  {
    id: 'prt-005',
    workOrderId: 'wo-002',
    tailNumber: 'N33333',
    partNumber: 'S3002-1',
    description: 'Right brake master cylinder — Cleveland',
    quantity: 1,
    unitCost: 342,
    supplier: 'Matco Mfg',
    poNumber: 'PO-2026-0314',
    orderedDate: '2026-03-22',
    etaDate: '2026-04-01',
    arrivedDate: null,
    installedDate: null,
    status: 'ordered',
    notes: 'Standard cylinder, should be compatible. Confirm P/N against IPC before installing.',
  },
  {
    id: 'prt-006',
    workOrderId: 'wo-002',
    tailNumber: 'N33333',
    partNumber: 'SE-1-4',
    description: 'Brake pad set (4-pack) — Cleveland',
    quantity: 1,
    unitCost: 78,
    supplier: 'Aircraft Spruce',
    poNumber: 'PO-2026-0313',
    orderedDate: '2026-03-22',
    etaDate: '2026-04-01',
    arrivedDate: '2026-03-27',
    installedDate: null,
    status: 'arrived',
    notes: 'In stock. Ready to install once master cylinder arrives.',
  },

  // ── wo-003 (N67890 pitot heat) ──
  {
    id: 'prt-007',
    workOrderId: 'wo-003',
    tailNumber: 'N67890',
    partNumber: '0411260',
    description: 'Pitot heat element assembly — Cessna/Garmin',
    quantity: 1,
    unitCost: 285,
    supplier: 'Cessna Parts Direct',
    poNumber: 'PO-2026-0309',
    orderedDate: '2026-03-17',
    etaDate: '2026-03-31',
    arrivedDate: null,
    installedDate: null,
    status: 'in_transit',
    notes: 'Confirmed tracking. ETA 2026-03-31. Work scheduled same day. MEL expires 2026-04-15.',
  },

  // ── wo-004 (N22222 autopilot — no parts ordered yet, awaiting diagnosis) ──
  {
    id: 'prt-008',
    workOrderId: 'wo-004',
    tailNumber: 'N22222',
    partNumber: 'TBD',
    description: 'GFC 700 altitude channel servo or PCB — pending diagnosis',
    quantity: 1,
    unitCost: 0,
    supplier: 'Garmin Aviation',
    poNumber: null,
    orderedDate: null,
    etaDate: null,
    arrivedDate: null,
    installedDate: null,
    status: 'not_ordered',
    notes: 'Awaiting avionics tech 2026-04-02 diagnosis before ordering. May be GSA 80 servo or GFC 700 controller module.',
  },

  // ── wo-005 (N11111 annual — consumables pre-staged) ──
  {
    id: 'prt-009',
    workOrderId: 'wo-005',
    tailNumber: 'N11111',
    partNumber: 'AEL15W50-QT',
    description: 'Engine oil 15W-50 (qty 8 qt)',
    quantity: 8,
    unitCost: 9.50,
    supplier: 'Aircraft Spruce',
    poNumber: 'PO-2026-0315',
    orderedDate: '2026-03-28',
    etaDate: '2026-03-30',
    arrivedDate: null,
    installedDate: null,
    status: 'ordered',
    notes: 'Standard consumable. Ordering ahead of inspection.',
  },
  {
    id: 'prt-010',
    workOrderId: 'wo-005',
    tailNumber: 'N11111',
    partNumber: 'LW-10971',
    description: 'Engine oil filter — Lycoming',
    quantity: 1,
    unitCost: 24,
    supplier: 'Aircraft Spruce',
    poNumber: 'PO-2026-0315',
    orderedDate: '2026-03-28',
    etaDate: '2026-03-30',
    arrivedDate: null,
    installedDate: null,
    status: 'ordered',
    notes: null,
  },
  {
    id: 'prt-011',
    workOrderId: 'wo-005',
    tailNumber: 'N11111',
    partNumber: 'SA-40',
    description: 'Spark plugs — Champion (set of 4)',
    quantity: 1,
    unitCost: 68,
    supplier: 'Aircraft Spruce',
    poNumber: null,
    orderedDate: null,
    etaDate: null,
    arrivedDate: null,
    installedDate: null,
    status: 'not_ordered',
    notes: 'Order only if gap/condition requires replacement at inspection.',
  },
  {
    id: 'prt-012',
    workOrderId: 'wo-006',
    tailNumber: 'N11111',
    partNumber: 'PAR-2044030-1',
    description: 'Fuel selector valve — Piper PA-28 replacement kit',
    quantity: 1,
    unitCost: 485,
    supplier: 'Piper Parts Direct',
    poNumber: null,
    orderedDate: null,
    etaDate: null,
    arrivedDate: null,
    installedDate: null,
    status: 'not_ordered',
    notes: 'Per AD 2024-11-03 / Piper SB-1298. Order only if inspection reveals improper detent. Quote obtained: $485.',
  },

  // ── wo-007 (N44444 100hr — consumables pre-staged) ──
  {
    id: 'prt-013',
    workOrderId: 'wo-007',
    tailNumber: 'N44444',
    partNumber: 'AEL20W50-QT',
    description: 'Engine oil 20W-50 (qty 24 qt — both engines)',
    quantity: 24,
    unitCost: 9.50,
    supplier: 'Aircraft Spruce',
    poNumber: 'PO-2026-0316',
    orderedDate: '2026-03-28',
    etaDate: '2026-04-03',
    arrivedDate: null,
    installedDate: null,
    status: 'ordered',
    notes: '12 qt per engine × 2 engines.',
  },
  {
    id: 'prt-014',
    workOrderId: 'wo-007',
    tailNumber: 'N44444',
    partNumber: 'OFP-64119',
    description: 'Oil filters — Continental (qty 2)',
    quantity: 2,
    unitCost: 38,
    supplier: 'Aircraft Spruce',
    poNumber: 'PO-2026-0316',
    orderedDate: '2026-03-28',
    etaDate: '2026-04-03',
    arrivedDate: null,
    installedDate: null,
    status: 'ordered',
    notes: null,
  },

  // ── wo-009 (N55555 heat cable — completed/installed) ──
  {
    id: 'prt-015',
    workOrderId: 'wo-009',
    tailNumber: 'N55555',
    partNumber: '0515087',
    description: 'Heat control cable assembly',
    quantity: 1,
    unitCost: 120,
    supplier: 'Aircraft Spruce',
    poNumber: 'PO-2026-0122',
    orderedDate: '2026-02-21',
    etaDate: '2026-02-24',
    arrivedDate: '2026-02-24',
    installedDate: '2026-02-25',
    status: 'installed',
    notes: null,
  },

  // ── wo-010 (N55555 annual — completed/installed) ──
  {
    id: 'prt-016',
    workOrderId: 'wo-010',
    tailNumber: 'N55555',
    partNumber: 'PW32680',
    description: 'Engine oil filter — PT6A',
    quantity: 1,
    unitCost: 42,
    supplier: 'P&WC Parts',
    poNumber: 'PO-2026-0110',
    orderedDate: '2026-02-12',
    etaDate: '2026-02-15',
    arrivedDate: '2026-02-15',
    installedDate: '2026-02-19',
    status: 'installed',
    notes: null,
  },
  {
    id: 'prt-017',
    workOrderId: 'wo-010',
    tailNumber: 'N55555',
    partNumber: '3030031-1',
    description: 'Fuel nozzle kit — C208B (set of 14)',
    quantity: 1,
    unitCost: 385,
    supplier: 'Cessna Parts Direct',
    poNumber: 'PO-2026-0110',
    orderedDate: '2026-02-12',
    etaDate: '2026-02-16',
    arrivedDate: '2026-02-16',
    installedDate: '2026-02-19',
    status: 'installed',
    notes: null,
  },
]

// ─── Inspection Schedule ───────────────────────────────────────────────────────
// One row per aircraft per inspection type.
// status: current | due_soon | overdue

export const mockInspectionSchedule = [
  // ── N12345 (BE58) ──
  { id: 'is-001', tailNumber: 'N12345', inspectionType: 'annual',
    regulatoryRef: '14 CFR 91.409(a)', intervalMonths: 12, intervalHours: null,
    dueSoonThresholdDays: 30, lastCompletedDate: '2026-02-04', lastCompletedHours: 2795,
    nextDueDate: '2027-02-04', status: 'current', notes: 'IA sign-off required' },
  { id: 'is-002', tailNumber: 'N12345', inspectionType: '100hr',
    regulatoryRef: '14 CFR 91.409(b)', intervalMonths: null, intervalHours: 100,
    dueSoonThresholdDays: 20, lastCompletedDate: '2026-02-18', lastCompletedHours: 2772,
    nextDueDate: '2026-05-28', status: 'current', notes: 'Commercial ops — 100hr required' },
  { id: 'is-003', tailNumber: 'N12345', inspectionType: 'altimeter_static',
    regulatoryRef: '14 CFR 91.411', intervalMonths: 24, intervalHours: null,
    dueSoonThresholdDays: 30, lastCompletedDate: '2026-02-04', lastCompletedHours: 2795,
    nextDueDate: '2028-02-04', status: 'current', notes: 'IFR ops — mandatory' },
  { id: 'is-004', tailNumber: 'N12345', inspectionType: 'transponder',
    regulatoryRef: '14 CFR 91.413', intervalMonths: 24, intervalHours: null,
    dueSoonThresholdDays: 30, lastCompletedDate: '2026-02-04', lastCompletedHours: 2795,
    nextDueDate: '2028-02-04', status: 'current', notes: null },
  { id: 'is-005', tailNumber: 'N12345', inspectionType: 'elt_inspection',
    regulatoryRef: '14 CFR 91.207(d)', intervalMonths: 12, intervalHours: null,
    dueSoonThresholdDays: 30, lastCompletedDate: '2026-02-04', lastCompletedHours: 2795,
    nextDueDate: '2027-02-04', status: 'current', notes: '406 MHz ELT' },
  { id: 'is-006', tailNumber: 'N12345', inspectionType: 'vor_check',
    regulatoryRef: '14 CFR 91.171', intervalMonths: null, intervalHours: null,
    dueSoonThresholdDays: 5, lastCompletedDate: '2026-03-15', lastCompletedHours: 2838,
    nextDueDate: '2026-04-14', status: 'current', notes: 'IFR — 30-day max' },

  // ── N67890 (C172S) ──
  { id: 'is-007', tailNumber: 'N67890', inspectionType: 'annual',
    regulatoryRef: '14 CFR 91.409(a)', intervalMonths: 12, intervalHours: null,
    dueSoonThresholdDays: 30, lastCompletedDate: '2025-09-22', lastCompletedHours: 958,
    nextDueDate: '2026-09-22', status: 'current', notes: null },
  { id: 'is-008', tailNumber: 'N67890', inspectionType: '100hr',
    regulatoryRef: '14 CFR 91.409(b)', intervalMonths: null, intervalHours: 100,
    dueSoonThresholdDays: 20, lastCompletedDate: '2026-01-25', lastCompletedHours: 1065,
    nextDueDate: '2026-05-05', status: 'current', notes: 'MEL on pitot heat — track carefully' },
  { id: 'is-009', tailNumber: 'N67890', inspectionType: 'altimeter_static',
    regulatoryRef: '14 CFR 91.411', intervalMonths: 24, intervalHours: null,
    dueSoonThresholdDays: 30, lastCompletedDate: '2025-09-22', lastCompletedHours: 958,
    nextDueDate: '2027-09-22', status: 'current', notes: null },
  { id: 'is-010', tailNumber: 'N67890', inspectionType: 'transponder',
    regulatoryRef: '14 CFR 91.413', intervalMonths: 24, intervalHours: null,
    dueSoonThresholdDays: 30, lastCompletedDate: '2025-09-22', lastCompletedHours: 958,
    nextDueDate: '2027-09-22', status: 'current', notes: null },
  { id: 'is-011', tailNumber: 'N67890', inspectionType: 'elt_inspection',
    regulatoryRef: '14 CFR 91.207(d)', intervalMonths: 12, intervalHours: null,
    dueSoonThresholdDays: 30, lastCompletedDate: '2025-09-22', lastCompletedHours: 958,
    nextDueDate: '2026-09-22', status: 'current', notes: null },
  { id: 'is-012', tailNumber: 'N67890', inspectionType: 'vor_check',
    regulatoryRef: '14 CFR 91.171', intervalMonths: null, intervalHours: null,
    dueSoonThresholdDays: 5, lastCompletedDate: '2026-03-10', lastCompletedHours: 1118,
    nextDueDate: '2026-04-09', status: 'current', notes: null },

  // ── N11111 (PA28) — MULTIPLE DUE SOON ──
  { id: 'is-013', tailNumber: 'N11111', inspectionType: 'annual',
    regulatoryRef: '14 CFR 91.409(a)', intervalMonths: 12, intervalHours: null,
    dueSoonThresholdDays: 30, lastCompletedDate: '2025-04-15', lastCompletedHours: 3075,
    nextDueDate: '2026-04-15', status: 'due_soon', notes: '18 days — schedule immediately' },
  { id: 'is-014', tailNumber: 'N11111', inspectionType: '100hr',
    regulatoryRef: '14 CFR 91.409(b)', intervalMonths: null, intervalHours: 100,
    dueSoonThresholdDays: 20, lastCompletedDate: '2026-01-02', lastCompletedHours: 3327,
    nextDueDate: '2026-04-02', status: 'due_soon', notes: '5 DAYS — CRITICAL' },
  { id: 'is-015', tailNumber: 'N11111', inspectionType: 'altimeter_static',
    regulatoryRef: '14 CFR 91.411', intervalMonths: 24, intervalHours: null,
    dueSoonThresholdDays: 30, lastCompletedDate: '2025-04-15', lastCompletedHours: 3075,
    nextDueDate: '2027-04-15', status: 'current', notes: null },
  { id: 'is-016', tailNumber: 'N11111', inspectionType: 'transponder',
    regulatoryRef: '14 CFR 91.413', intervalMonths: 24, intervalHours: null,
    dueSoonThresholdDays: 30, lastCompletedDate: '2025-04-15', lastCompletedHours: 3075,
    nextDueDate: '2027-04-15', status: 'current', notes: null },
  { id: 'is-017', tailNumber: 'N11111', inspectionType: 'elt_inspection',
    regulatoryRef: '14 CFR 91.207(d)', intervalMonths: 12, intervalHours: null,
    dueSoonThresholdDays: 30, lastCompletedDate: '2025-04-15', lastCompletedHours: 3075,
    nextDueDate: '2026-04-15', status: 'due_soon', notes: 'Due same day as annual' },
  { id: 'is-018', tailNumber: 'N11111', inspectionType: 'vor_check',
    regulatoryRef: '14 CFR 91.171', intervalMonths: null, intervalHours: null,
    dueSoonThresholdDays: 5, lastCompletedDate: '2026-03-05', lastCompletedHours: 3408,
    nextDueDate: '2026-04-04', status: 'current', notes: null },

  // ── N22222 (C208) ──
  { id: 'is-019', tailNumber: 'N22222', inspectionType: 'annual',
    regulatoryRef: '14 CFR 91.409(a)', intervalMonths: 12, intervalHours: null,
    dueSoonThresholdDays: 30, lastCompletedDate: '2026-01-20', lastCompletedHours: 5160,
    nextDueDate: '2027-01-20', status: 'current', notes: null },
  { id: 'is-020', tailNumber: 'N22222', inspectionType: '100hr',
    regulatoryRef: '14 CFR 91.409(b)', intervalMonths: null, intervalHours: 100,
    dueSoonThresholdDays: 20, lastCompletedDate: '2026-02-10', lastCompletedHours: 5180,
    nextDueDate: '2026-05-20', status: 'current', notes: 'Turboprop — PT6A per manufacturer' },
  { id: 'is-021', tailNumber: 'N22222', inspectionType: 'altimeter_static',
    regulatoryRef: '14 CFR 91.411', intervalMonths: 24, intervalHours: null,
    dueSoonThresholdDays: 30, lastCompletedDate: '2026-01-20', lastCompletedHours: 5160,
    nextDueDate: '2028-01-20', status: 'current', notes: null },
  { id: 'is-022', tailNumber: 'N22222', inspectionType: 'transponder',
    regulatoryRef: '14 CFR 91.413', intervalMonths: 24, intervalHours: null,
    dueSoonThresholdDays: 30, lastCompletedDate: '2026-01-20', lastCompletedHours: 5160,
    nextDueDate: '2028-01-20', status: 'current', notes: null },
  { id: 'is-023', tailNumber: 'N22222', inspectionType: 'elt_inspection',
    regulatoryRef: '14 CFR 91.207(d)', intervalMonths: 12, intervalHours: null,
    dueSoonThresholdDays: 30, lastCompletedDate: '2026-01-20', lastCompletedHours: 5160,
    nextDueDate: '2027-01-20', status: 'current', notes: null },

  // ── N33333 (C172N) — GROUNDED + OVERDUE ──
  { id: 'is-024', tailNumber: 'N33333', inspectionType: 'annual',
    regulatoryRef: '14 CFR 91.409(a)', intervalMonths: 12, intervalHours: null,
    dueSoonThresholdDays: 30, lastCompletedDate: '2025-03-01', lastCompletedHours: 6700,
    nextDueDate: '2026-03-01', status: 'overdue', notes: '27 DAYS OVERDUE — aircraft grounded' },
  { id: 'is-025', tailNumber: 'N33333', inspectionType: '100hr',
    regulatoryRef: '14 CFR 91.409(b)', intervalMonths: null, intervalHours: 100,
    dueSoonThresholdDays: 20, lastCompletedDate: '2025-11-29', lastCompletedHours: 6700,
    nextDueDate: '2026-03-11', status: 'overdue', notes: '17 DAYS OVERDUE' },
  { id: 'is-026', tailNumber: 'N33333', inspectionType: 'altimeter_static',
    regulatoryRef: '14 CFR 91.411', intervalMonths: 24, intervalHours: null,
    dueSoonThresholdDays: 30, lastCompletedDate: '2025-03-01', lastCompletedHours: 6700,
    nextDueDate: '2027-03-01', status: 'current', notes: 'IFR ops suspended — aircraft grounded' },
  { id: 'is-027', tailNumber: 'N33333', inspectionType: 'transponder',
    regulatoryRef: '14 CFR 91.413', intervalMonths: 24, intervalHours: null,
    dueSoonThresholdDays: 30, lastCompletedDate: '2025-03-01', lastCompletedHours: 6700,
    nextDueDate: '2027-03-01', status: 'current', notes: null },
  { id: 'is-028', tailNumber: 'N33333', inspectionType: 'elt_inspection',
    regulatoryRef: '14 CFR 91.207(d)', intervalMonths: 12, intervalHours: null,
    dueSoonThresholdDays: 30, lastCompletedDate: '2025-03-01', lastCompletedHours: 6700,
    nextDueDate: '2026-03-01', status: 'overdue', notes: 'Bundle with annual when scheduling' },

  // ── N44444 (PA34) — 100hr due soon ──
  { id: 'is-029', tailNumber: 'N44444', inspectionType: 'annual',
    regulatoryRef: '14 CFR 91.409(a)', intervalMonths: 12, intervalHours: null,
    dueSoonThresholdDays: 30, lastCompletedDate: '2025-12-21', lastCompletedHours: 2040,
    nextDueDate: '2026-12-21', status: 'current', notes: null },
  { id: 'is-030', tailNumber: 'N44444', inspectionType: '100hr',
    regulatoryRef: '14 CFR 91.409(b)', intervalMonths: null, intervalHours: 100,
    dueSoonThresholdDays: 20, lastCompletedDate: '2026-01-14', lastCompletedHours: 2040,
    nextDueDate: '2026-04-25', status: 'due_soon', notes: '28 days — schedule this week' },
  { id: 'is-031', tailNumber: 'N44444', inspectionType: 'altimeter_static',
    regulatoryRef: '14 CFR 91.411', intervalMonths: 24, intervalHours: null,
    dueSoonThresholdDays: 30, lastCompletedDate: '2025-12-21', lastCompletedHours: 2040,
    nextDueDate: '2027-12-21', status: 'current', notes: null },
  { id: 'is-032', tailNumber: 'N44444', inspectionType: 'transponder',
    regulatoryRef: '14 CFR 91.413', intervalMonths: 24, intervalHours: null,
    dueSoonThresholdDays: 30, lastCompletedDate: '2025-12-21', lastCompletedHours: 2040,
    nextDueDate: '2027-12-21', status: 'current', notes: null },
  { id: 'is-033', tailNumber: 'N44444', inspectionType: 'elt_inspection',
    regulatoryRef: '14 CFR 91.207(d)', intervalMonths: 12, intervalHours: null,
    dueSoonThresholdDays: 30, lastCompletedDate: '2025-12-21', lastCompletedHours: 2040,
    nextDueDate: '2026-12-21', status: 'current', notes: null },
  { id: 'is-034', tailNumber: 'N44444', inspectionType: 'vor_check',
    regulatoryRef: '14 CFR 91.171', intervalMonths: null, intervalHours: null,
    dueSoonThresholdDays: 5, lastCompletedDate: '2026-03-12', lastCompletedHours: 2103,
    nextDueDate: '2026-04-11', status: 'current', notes: null },

  // ── N55555 (C208B) ──
  { id: 'is-035', tailNumber: 'N55555', inspectionType: 'annual',
    regulatoryRef: '14 CFR 91.409(a)', intervalMonths: 12, intervalHours: null,
    dueSoonThresholdDays: 30, lastCompletedDate: '2026-02-19', lastCompletedHours: 1862,
    nextDueDate: '2027-02-19', status: 'current', notes: null },
  { id: 'is-036', tailNumber: 'N55555', inspectionType: '100hr',
    regulatoryRef: '14 CFR 91.409(b)', intervalMonths: null, intervalHours: 100,
    dueSoonThresholdDays: 20, lastCompletedDate: '2026-02-19', lastCompletedHours: 1862,
    nextDueDate: '2026-06-08', status: 'current', notes: null },
  { id: 'is-037', tailNumber: 'N55555', inspectionType: 'altimeter_static',
    regulatoryRef: '14 CFR 91.411', intervalMonths: 24, intervalHours: null,
    dueSoonThresholdDays: 30, lastCompletedDate: '2026-02-19', lastCompletedHours: 1862,
    nextDueDate: '2028-02-19', status: 'current', notes: null },
  { id: 'is-038', tailNumber: 'N55555', inspectionType: 'transponder',
    regulatoryRef: '14 CFR 91.413', intervalMonths: 24, intervalHours: null,
    dueSoonThresholdDays: 30, lastCompletedDate: '2026-02-19', lastCompletedHours: 1862,
    nextDueDate: '2028-02-19', status: 'current', notes: null },
  { id: 'is-039', tailNumber: 'N55555', inspectionType: 'elt_inspection',
    regulatoryRef: '14 CFR 91.207(d)', intervalMonths: 12, intervalHours: null,
    dueSoonThresholdDays: 30, lastCompletedDate: '2026-02-19', lastCompletedHours: 1862,
    nextDueDate: '2027-02-19', status: 'current', notes: null },
]

// ─── Maintenance Records (Logbook Entries) ────────────────────────────────────
// Per 14 CFR 43.9 & 43.11

export const mockMaintenanceRecords = [
  {
    id: 'mr-001',
    tailNumber: 'N12345',
    recordDate: '2026-02-04',
    type: 'annual',
    description: 'Annual inspection performed per 14 CFR 91.409(a) and Beechcraft Baron 58 Maintenance Manual Chapter 5.',
    findings: 'Left magneto timing advanced 2°. Left main tire worn to wear bars. All other systems within limits.',
    correctiveAction: 'Left magneto timing reset to 25° BTDC. Left main tire replaced — P/N 0756010-7.',
    airframeHoursAtService: 2795,
    mechanicName: 'Sarah Cole',
    mechanicCertificate: 'A&P/IA',
    certificateNumber: '3987612',
    returnToServiceDate: '2026-02-04',
    partsReplaced: JSON.stringify([
      { partNumber: '0756010-7', description: 'Main wheel tire 6.00×6', quantity: 1, cost: 185 },
    ]),
    workOrderId: null,
    regulatoryRef: '14 CFR 43.9, 43.11, 91.409(a)',
  },
  {
    id: 'mr-002',
    tailNumber: 'N55555',
    recordDate: '2026-02-19',
    type: 'annual',
    description: 'Combined annual + 100hr inspection. C208B Grand Caravan MM. PT6A-114A engine borescope inspection.',
    findings: 'All inspection items within limits. Engine borescope: combustion liners and turbine blades satisfactory. No hot-section distress observed.',
    correctiveAction: 'Engine oil and filter changed. Fuel nozzles cleaned and flow-tested. Gear selector detents lubricated.',
    airframeHoursAtService: 1862,
    mechanicName: 'Sarah Cole',
    mechanicCertificate: 'A&P/IA',
    certificateNumber: '3987612',
    returnToServiceDate: '2026-02-19',
    partsReplaced: JSON.stringify([
      { partNumber: 'PW32680', description: 'Engine oil filter', quantity: 1, cost: 42 },
      { partNumber: '3030031-1', description: 'Fuel nozzle kit (set of 14)', quantity: 1, cost: 385 },
    ]),
    workOrderId: 'wo-010',
    regulatoryRef: '14 CFR 43.9, 43.11, 91.409(a)(b)',
  },
  {
    id: 'mr-003',
    tailNumber: 'N44444',
    recordDate: '2026-01-18',
    type: 'squawk_repair',
    description: 'Right main gear door slow to close — actuator linkage adjustment and hinge lubrication.',
    findings: 'Actuator rod end binding. LH gear door hinge pivot dry. Right gear door closing time 4 sec.',
    correctiveAction: 'Adjusted actuator rod end per PA-34 AMM Ch 32. Lubricated all gear door hinges. Gear door close time: 1.8 sec. Functional check: 5 cycles, satisfactory.',
    airframeHoursAtService: 2090,
    mechanicName: 'Mike Ferris',
    mechanicCertificate: 'A&P',
    certificateNumber: '4201988',
    returnToServiceDate: '2026-01-18',
    partsReplaced: null,
    workOrderId: 'wo-008',
    regulatoryRef: '14 CFR 43.9',
  },
  {
    id: 'mr-004',
    tailNumber: 'N55555',
    recordDate: '2026-02-25',
    type: 'squawk_repair',
    description: 'Cabin heat control cable replacement.',
    findings: 'Cable sheath cracked at cockpit end. Inner cable frayed — friction causing stiff control feel.',
    correctiveAction: 'Replaced heater control cable assembly P/N 0515087. Full travel: smooth operation confirmed. No binding.',
    airframeHoursAtService: 1880,
    mechanicName: 'Sarah Cole',
    mechanicCertificate: 'A&P/IA',
    certificateNumber: '3987612',
    returnToServiceDate: '2026-02-25',
    partsReplaced: JSON.stringify([
      { partNumber: '0515087', description: 'Heat control cable assembly', quantity: 1, cost: 120 },
    ]),
    workOrderId: 'wo-009',
    regulatoryRef: '14 CFR 43.9',
  },
  {
    id: 'mr-005',
    tailNumber: 'N22222',
    recordDate: '2026-01-20',
    type: 'annual',
    description: 'Annual + 100hr combined inspection, C208 Caravan MM. PT6A-114A per PT6A Maintenance Manual.',
    findings: 'Prop de-ice boot left blade shows minor erosion — serviceable limits. All AD compliance verified current.',
    correctiveAction: 'Engine oil and filters changed x2. PT6A compressor wash performed. Prop de-ice boot: within limits, monitor.',
    airframeHoursAtService: 5160,
    mechanicName: 'Sarah Cole',
    mechanicCertificate: 'A&P/IA',
    certificateNumber: '3987612',
    returnToServiceDate: '2026-01-20',
    partsReplaced: JSON.stringify([
      { partNumber: 'MS9021-275', description: 'Engine oil filter (2)', quantity: 2, cost: 84 },
    ]),
    workOrderId: null,
    regulatoryRef: '14 CFR 43.9, 43.11, 91.409(a)(b)',
  },
]

// ─── Component TBO Tracking ───────────────────────────────────────────────────
// status: normal | monitoring | due_soon | overdue
// life_pct = (currentAirframeHours - hoursAtInstall) / tboHours * 100

export const mockComponentTbo = [
  // ── N12345 (BE58) — Continental IO-550-C engines, TBO 1700h ──
  {
    id: 'tbo-001',
    tailNumber: 'N12345',
    component: 'engine_1',
    componentLabel: 'L Engine — Continental IO-550-C',
    manufacturer: 'Continental Motors',
    model: 'IO-550-C',
    serialNumber: '499182-R',
    installDate: '2021-08-15',
    hoursAtInstall: 1140,   // hours on airframe when engine installed (post-overhaul)
    tboHours: 1700,
    tboCalendarMonths: null,
    nextTboDate: null,
    dueSoonThresholdHours: 150,
    status: 'normal',
    notes: 'Factory remanufactured 2021. Currently 1700h TBO per Continental SB96-11.',
  },
  {
    id: 'tbo-002',
    tailNumber: 'N12345',
    component: 'engine_2',
    componentLabel: 'R Engine — Continental IO-550-C',
    manufacturer: 'Continental Motors',
    model: 'IO-550-C',
    serialNumber: '499183-R',
    installDate: '2021-08-15',
    hoursAtInstall: 1140,
    tboHours: 1700,
    tboCalendarMonths: null,
    nextTboDate: null,
    dueSoonThresholdHours: 150,
    status: 'normal',
    notes: 'Factory remanufactured 2021. Run-of-life matched with engine_1.',
  },
  {
    id: 'tbo-003',
    tailNumber: 'N12345',
    component: 'prop_1',
    componentLabel: 'L Prop — Hartzell HC-E3YR-2ALF',
    manufacturer: 'Hartzell',
    model: 'HC-E3YR-2ALF',
    serialNumber: 'DG6734',
    installDate: '2021-08-15',
    hoursAtInstall: 1140,
    tboHours: 2400,
    tboCalendarMonths: 72,
    nextTboDate: '2027-08-15',
    dueSoonThresholdHours: 200,
    status: 'normal',
    notes: 'Calendar TBO: 6 years (2027-08-15) or 2400 hours, whichever first.',
  },

  // ── N22222 (C208) — PT6A-114A, TBO 3600h ──
  {
    id: 'tbo-004',
    tailNumber: 'N22222',
    component: 'engine_1',
    componentLabel: 'Engine — PT6A-114A',
    manufacturer: 'Pratt & Whitney Canada',
    model: 'PT6A-114A',
    serialNumber: 'PCE-PA0443',
    installDate: '2019-04-10',
    hoursAtInstall: 3480,    // hours on airframe when engine installed (post-overhaul)
    tboHours: 3600,
    tboCalendarMonths: null,
    nextTboDate: null,
    dueSoonThresholdHours: 300,
    status: 'monitoring',
    notes: 'Engine time since overhaul: 1740h. TBO 3600h. 1860h remaining. Hot section inspection due per SB 1780 at 3000h total time.',
  },
  {
    id: 'tbo-005',
    tailNumber: 'N22222',
    component: 'prop_1',
    componentLabel: 'Prop — Hartzell HC-B3TN-3D',
    manufacturer: 'Hartzell',
    model: 'HC-B3TN-3D',
    serialNumber: 'HQ8231',
    installDate: '2019-04-10',
    hoursAtInstall: 3480,
    tboHours: 3000,
    tboCalendarMonths: 72,
    nextTboDate: '2025-04-10',
    dueSoonThresholdHours: 200,
    status: 'due_soon',
    notes: 'CALENDAR TBO OVERDUE — next TBO date was 2025-04-10. Must be scheduled. Total time: 1740h/3000h.',
  },

  // ── N44444 (PA34) — Continental TSIO-360-RB, TBO 1800h ──
  {
    id: 'tbo-006',
    tailNumber: 'N44444',
    component: 'engine_1',
    componentLabel: 'L Engine — Continental TSIO-360-RB',
    manufacturer: 'Continental Motors',
    model: 'TSIO-360-RB',
    serialNumber: '640121-R',
    installDate: '2022-03-01',
    hoursAtInstall: 1640,
    tboHours: 1800,
    tboCalendarMonths: null,
    nextTboDate: null,
    dueSoonThresholdHours: 150,
    status: 'normal',
    notes: 'TBO 1800h per Continental SB96-11C. Hours since overhaul: 465h.',
  },
  {
    id: 'tbo-007',
    tailNumber: 'N44444',
    component: 'engine_2',
    componentLabel: 'R Engine — Continental TSIO-360-RB',
    manufacturer: 'Continental Motors',
    model: 'TSIO-360-RB',
    serialNumber: '640122-R',
    installDate: '2022-03-01',
    hoursAtInstall: 1640,
    tboHours: 1800,
    tboCalendarMonths: null,
    nextTboDate: null,
    dueSoonThresholdHours: 150,
    status: 'normal',
    notes: 'Matched to engine_1 overhaul cycle.',
  },

  // ── N55555 (C208B) — PT6A-114A, TBO 3600h ──
  {
    id: 'tbo-008',
    tailNumber: 'N55555',
    component: 'engine_1',
    componentLabel: 'Engine — PT6A-114A',
    manufacturer: 'Pratt & Whitney Canada',
    model: 'PT6A-114A',
    serialNumber: 'PCE-PA0891',
    installDate: '2021-01-15',
    hoursAtInstall: 0,
    tboHours: 3600,
    tboCalendarMonths: null,
    nextTboDate: null,
    dueSoonThresholdHours: 300,
    status: 'normal',
    notes: 'New engine installed at aircraft delivery. Hours since new: 1890h. 1710h remaining to TBO.',
  },
  {
    id: 'tbo-009',
    tailNumber: 'N55555',
    component: 'prop_1',
    componentLabel: 'Prop — Hartzell HC-B3TN-3D',
    manufacturer: 'Hartzell',
    model: 'HC-B3TN-3D',
    serialNumber: 'HQ9915',
    installDate: '2021-01-15',
    hoursAtInstall: 0,
    tboHours: 3000,
    tboCalendarMonths: 72,
    nextTboDate: '2027-01-15',
    dueSoonThresholdHours: 200,
    status: 'normal',
    notes: null,
  },
]

// ─── Fleet Maintenance Summary (Scorecard) ────────────────────────────────────

export const mockMaintenanceSummary = {
  // Squawks
  openSquawks:          mockSquawks.filter((s) => s.status === 'open' || s.status === 'in_progress').length,
  groundingSquawks:     mockSquawks.filter((s) => s.severity === 'grounding' && s.status !== 'closed').length,
  melDeferred:          mockSquawks.filter((s) => s.status === 'deferred_mel').length,

  // Work Orders
  workOrdersOpen:       mockWorkOrders.filter((w) => w.status !== 'completed' && w.status !== 'cancelled').length,
  workOrdersAog:        mockWorkOrders.filter((w) => w.priority === 'aog' && w.status !== 'completed').length,
  workOrdersUrgent:     mockWorkOrders.filter((w) => w.priority === 'urgent' && w.status !== 'completed').length,

  // Inspections
  inspectionsOverdue:   mockInspectionSchedule.filter((i) => i.status === 'overdue').length,
  inspectionsDueSoon:   mockInspectionSchedule.filter((i) => i.status === 'due_soon').length,

  // Components
  tboOverdue:           mockComponentTbo.filter((t) => t.status === 'overdue').length,
  tboDueSoon:           mockComponentTbo.filter((t) => t.status === 'due_soon').length,

  // Parts
  partsOrdered:         mockParts.filter((p) => p.status === 'ordered').length,
  partsInTransit:       mockParts.filter((p) => p.status === 'in_transit').length,
  partsArrived:         mockParts.filter((p) => p.status === 'arrived').length,
  partsBackordered:     mockParts.filter((p) => p.status === 'backordered').length,
  partsNotOrdered:      mockParts.filter((p) => p.status === 'not_ordered' && mockWorkOrders.find((w) => w.id === p.workOrderId && w.status !== 'completed')).length,
}
